// Code generated by protoc-gen-gogo. DO NOT EDIT.
// source: GameCtl.proto

package proto

import (
	fmt "fmt"
	math "math"
	proto "github.com/gogo/protobuf/proto"
	golang_proto "github.com/golang/protobuf/proto"
	_ "github.com/gogo/protobuf/gogoproto"
	_ "github.com/gogo/protobuf/types"
	_ "github.com/gogo/googleapis/google/api"
	_ "github.com/grpc-ecosystem/grpc-gateway/protoc-gen-swagger/options"
	github_com_mwitkow_go_proto_validators "github.com/mwitkow/go-proto-validators"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = golang_proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

func (this *ErrorMsg) Validate() error {
	return nil
}
func (this *RoomListReq) Validate() error {
	return nil
}
func (this *RoomListResp) Validate() error {
	for _, item := range this.Result {
		if item != nil {
			if err := github_com_mwitkow_go_proto_validators.CallValidatorIfExists(item); err != nil {
				return github_com_mwitkow_go_proto_validators.FieldError("Result", err)
			}
		}
	}
	if this.ErrorMsg != nil {
		if err := github_com_mwitkow_go_proto_validators.CallValidatorIfExists(this.ErrorMsg); err != nil {
			return github_com_mwitkow_go_proto_validators.FieldError("ErrorMsg", err)
		}
	}
	return nil
}
func (this *RoomCreateReq) Validate() error {
	return nil
}
func (this *RoomCreateResp) Validate() error {
	if oneOfNester, ok := this.GetResponseMsg().(*RoomCreateResp_CellStatus); ok {
		if oneOfNester.CellStatus != nil {
			if err := github_com_mwitkow_go_proto_validators.CallValidatorIfExists(oneOfNester.CellStatus); err != nil {
				return github_com_mwitkow_go_proto_validators.FieldError("CellStatus", err)
			}
		}
	}
	if oneOfNester, ok := this.GetResponseMsg().(*RoomCreateResp_ErrorMsg); ok {
		if oneOfNester.ErrorMsg != nil {
			if err := github_com_mwitkow_go_proto_validators.CallValidatorIfExists(oneOfNester.ErrorMsg); err != nil {
				return github_com_mwitkow_go_proto_validators.FieldError("ErrorMsg", err)
			}
		}
	}
	return nil
}
func (this *RoomReq) Validate() error {
	return nil
}
func (this *RoomResp) Validate() error {
	if oneOfNester, ok := this.GetResponseMsg().(*RoomResp_RoomInfo); ok {
		if oneOfNester.RoomInfo != nil {
			if err := github_com_mwitkow_go_proto_validators.CallValidatorIfExists(oneOfNester.RoomInfo); err != nil {
				return github_com_mwitkow_go_proto_validators.FieldError("RoomInfo", err)
			}
		}
	}
	if oneOfNester, ok := this.GetResponseMsg().(*RoomResp_Error); ok {
		if oneOfNester.Error != nil {
			if err := github_com_mwitkow_go_proto_validators.CallValidatorIfExists(oneOfNester.Error); err != nil {
				return github_com_mwitkow_go_proto_validators.FieldError("Error", err)
			}
		}
	}
	return nil
}
func (this *Room) Validate() error {
	for _, item := range this.CellStatus {
		if item != nil {
			if err := github_com_mwitkow_go_proto_validators.CallValidatorIfExists(item); err != nil {
				return github_com_mwitkow_go_proto_validators.FieldError("CellStatus", err)
			}
		}
	}
	return nil
}
func (this *CellStatus) Validate() error {
	return nil
}
func (this *CellStatusReq) Validate() error {
	if oneOfNester, ok := this.GetPlayer().(*CellStatusReq_CellStatus); ok {
		if oneOfNester.CellStatus != nil {
			if err := github_com_mwitkow_go_proto_validators.CallValidatorIfExists(oneOfNester.CellStatus); err != nil {
				return github_com_mwitkow_go_proto_validators.FieldError("CellStatus", err)
			}
		}
	}
	return nil
}
func (this *CellStatusResp) Validate() error {
	if oneOfNester, ok := this.GetResponseMsg().(*CellStatusResp_CellStatus); ok {
		if oneOfNester.CellStatus != nil {
			if err := github_com_mwitkow_go_proto_validators.CallValidatorIfExists(oneOfNester.CellStatus); err != nil {
				return github_com_mwitkow_go_proto_validators.FieldError("CellStatus", err)
			}
		}
	}
	if oneOfNester, ok := this.GetResponseMsg().(*CellStatusResp_ErrorMsg); ok {
		if oneOfNester.ErrorMsg != nil {
			if err := github_com_mwitkow_go_proto_validators.CallValidatorIfExists(oneOfNester.ErrorMsg); err != nil {
				return github_com_mwitkow_go_proto_validators.FieldError("ErrorMsg", err)
			}
		}
	}
	return nil
}
