// Code generated by protoc-gen-go. DO NOT EDIT.
// source: message.proto

package proto

import (
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

type RoomStatus int32

const (
	RoomStatus_ON_INIT    RoomStatus = 0
	RoomStatus_ON_WAIT    RoomStatus = 1
	RoomStatus_ON_START   RoomStatus = 2
	RoomStatus_ON_END     RoomStatus = 3
	RoomStatus_ON_DESTROY RoomStatus = 4
)

var RoomStatus_name = map[int32]string{
	0: "ON_INIT",
	1: "ON_WAIT",
	2: "ON_START",
	3: "ON_END",
	4: "ON_DESTROY",
}

var RoomStatus_value = map[string]int32{
	"ON_INIT":    0,
	"ON_WAIT":    1,
	"ON_START":   2,
	"ON_END":     3,
	"ON_DESTROY": 4,
}

func (x RoomStatus) String() string {
	return proto.EnumName(RoomStatus_name, int32(x))
}

func (RoomStatus) EnumDescriptor() ([]byte, []int) {
	return fileDescriptor_33c57e4bae7b9afd, []int{0}
}

type RoomMsg_MsgType int32

const (
	RoomMsg_USER_TEXT     RoomMsg_MsgType = 0
	RoomMsg_USER_STRICKER RoomMsg_MsgType = 1
	RoomMsg_SYSTEM_INFO   RoomMsg_MsgType = 2
	RoomMsg_SYSTEM_WARN   RoomMsg_MsgType = 3
	RoomMsg_SYSTEM_ERR    RoomMsg_MsgType = 4
)

var RoomMsg_MsgType_name = map[int32]string{
	0: "USER_TEXT",
	1: "USER_STRICKER",
	2: "SYSTEM_INFO",
	3: "SYSTEM_WARN",
	4: "SYSTEM_ERR",
}

var RoomMsg_MsgType_value = map[string]int32{
	"USER_TEXT":     0,
	"USER_STRICKER": 1,
	"SYSTEM_INFO":   2,
	"SYSTEM_WARN":   3,
	"SYSTEM_ERR":    4,
}

func (x RoomMsg_MsgType) String() string {
	return proto.EnumName(RoomMsg_MsgType_name, int32(x))
}

func (RoomMsg_MsgType) EnumDescriptor() ([]byte, []int) {
	return fileDescriptor_33c57e4bae7b9afd, []int{3, 0}
}

type RoomUpdateCardReq_PlayerSide int32

const (
	RoomUpdateCardReq_HOST   RoomUpdateCardReq_PlayerSide = 0
	RoomUpdateCardReq_DUELER RoomUpdateCardReq_PlayerSide = 1
)

var RoomUpdateCardReq_PlayerSide_name = map[int32]string{
	0: "HOST",
	1: "DUELER",
}

var RoomUpdateCardReq_PlayerSide_value = map[string]int32{
	"HOST":   0,
	"DUELER": 1,
}

func (x RoomUpdateCardReq_PlayerSide) String() string {
	return proto.EnumName(RoomUpdateCardReq_PlayerSide_name, int32(x))
}

func (RoomUpdateCardReq_PlayerSide) EnumDescriptor() ([]byte, []int) {
	return fileDescriptor_33c57e4bae7b9afd, []int{7, 0}
}

// RmCharCardInfo
//      Basic Character Card Infomation
type RmCharCardInfo struct {
	CardId               int32    `protobuf:"varint,1,opt,name=card_id,json=cardId,proto3" json:"card_id,omitempty"`
	Level                int32    `protobuf:"varint,2,opt,name=level,proto3" json:"level,omitempty"`
	Rare                 int32    `protobuf:"varint,3,opt,name=rare,proto3" json:"rare,omitempty"`
	Cost                 int32    `protobuf:"varint,4,opt,name=cost,proto3" json:"cost,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *RmCharCardInfo) Reset()         { *m = RmCharCardInfo{} }
func (m *RmCharCardInfo) String() string { return proto.CompactTextString(m) }
func (*RmCharCardInfo) ProtoMessage()    {}
func (*RmCharCardInfo) Descriptor() ([]byte, []int) {
	return fileDescriptor_33c57e4bae7b9afd, []int{0}
}

func (m *RmCharCardInfo) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_RmCharCardInfo.Unmarshal(m, b)
}
func (m *RmCharCardInfo) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_RmCharCardInfo.Marshal(b, m, deterministic)
}
func (m *RmCharCardInfo) XXX_Merge(src proto.Message) {
	xxx_messageInfo_RmCharCardInfo.Merge(m, src)
}
func (m *RmCharCardInfo) XXX_Size() int {
	return xxx_messageInfo_RmCharCardInfo.Size(m)
}
func (m *RmCharCardInfo) XXX_DiscardUnknown() {
	xxx_messageInfo_RmCharCardInfo.DiscardUnknown(m)
}

var xxx_messageInfo_RmCharCardInfo proto.InternalMessageInfo

func (m *RmCharCardInfo) GetCardId() int32 {
	if m != nil {
		return m.CardId
	}
	return 0
}

func (m *RmCharCardInfo) GetLevel() int32 {
	if m != nil {
		return m.Level
	}
	return 0
}

func (m *RmCharCardInfo) GetRare() int32 {
	if m != nil {
		return m.Rare
	}
	return 0
}

func (m *RmCharCardInfo) GetCost() int32 {
	if m != nil {
		return m.Cost
	}
	return 0
}

//*
//RmUserInfo :
//User basic Information for room info displaying
type RmUserInfo struct {
	Id                   string   `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Name                 string   `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	Level                int32    `protobuf:"varint,3,opt,name=level,proto3" json:"level,omitempty"`
	AvatIcon             string   `protobuf:"bytes,4,opt,name=avat_icon,json=avatIcon,proto3" json:"avat_icon,omitempty"`
	Title                string   `protobuf:"bytes,5,opt,name=title,proto3" json:"title,omitempty"`
	Rank                 int32    `protobuf:"varint,6,opt,name=rank,proto3" json:"rank,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *RmUserInfo) Reset()         { *m = RmUserInfo{} }
func (m *RmUserInfo) String() string { return proto.CompactTextString(m) }
func (*RmUserInfo) ProtoMessage()    {}
func (*RmUserInfo) Descriptor() ([]byte, []int) {
	return fileDescriptor_33c57e4bae7b9afd, []int{1}
}

func (m *RmUserInfo) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_RmUserInfo.Unmarshal(m, b)
}
func (m *RmUserInfo) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_RmUserInfo.Marshal(b, m, deterministic)
}
func (m *RmUserInfo) XXX_Merge(src proto.Message) {
	xxx_messageInfo_RmUserInfo.Merge(m, src)
}
func (m *RmUserInfo) XXX_Size() int {
	return xxx_messageInfo_RmUserInfo.Size(m)
}
func (m *RmUserInfo) XXX_DiscardUnknown() {
	xxx_messageInfo_RmUserInfo.DiscardUnknown(m)
}

var xxx_messageInfo_RmUserInfo proto.InternalMessageInfo

func (m *RmUserInfo) GetId() string {
	if m != nil {
		return m.Id
	}
	return ""
}

func (m *RmUserInfo) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

func (m *RmUserInfo) GetLevel() int32 {
	if m != nil {
		return m.Level
	}
	return 0
}

func (m *RmUserInfo) GetAvatIcon() string {
	if m != nil {
		return m.AvatIcon
	}
	return ""
}

func (m *RmUserInfo) GetTitle() string {
	if m != nil {
		return m.Title
	}
	return ""
}

func (m *RmUserInfo) GetRank() int32 {
	if m != nil {
		return m.Rank
	}
	return 0
}

//*
//Room :
//Room Detail Information
type Room struct {
	// Room-id the id
	Id string `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	// Room-Key the id
	Key string `protobuf:"bytes,2,opt,name=key,proto3" json:"key,omitempty"`
	// Room Password
	Password string `protobuf:"bytes,3,opt,name=password,proto3" json:"password,omitempty"`
	// User-info for room-host player
	Host *RmUserInfo `protobuf:"bytes,4,opt,name=host,proto3" json:"host,omitempty"`
	// User-info for dueler-player
	Dueler *RmUserInfo `protobuf:"bytes,5,opt,name=dueler,proto3" json:"dueler,omitempty"`
	// Rooms Status
	Status RoomStatus `protobuf:"varint,7,opt,name=status,proto3,enum=ULZProto.RoomStatus" json:"status,omitempty"`
	// Turns number of Game Duel
	Turns int32 `protobuf:"varint,8,opt,name=turns,proto3" json:"turns,omitempty"`
	// Limitation for total Card-Deck
	CostLimitMax int32 `protobuf:"varint,9,opt,name=cost_limit_max,json=costLimitMax,proto3" json:"cost_limit_max,omitempty"`
	CostLimitMin int32 `protobuf:"varint,10,opt,name=cost_limit_min,json=costLimitMin,proto3" json:"cost_limit_min,omitempty"`
	// Limitation for Charecter Card Cost
	CharCardLimitMax *RmCharCardInfo `protobuf:"bytes,11,opt,name=char_card_limit_max,json=charCardLimitMax,proto3" json:"char_card_limit_max,omitempty"`
	CharCardLimitMin *RmCharCardInfo `protobuf:"bytes,12,opt,name=char_card_limit_min,json=charCardLimitMin,proto3" json:"char_card_limit_min,omitempty"`
	// 1vs1 or 3vs3
	CharCardNvn int32 `protobuf:"varint,13,opt,name=char_card_nvn,json=charCardNvn,proto3" json:"char_card_nvn,omitempty"`
	// host-inst
	HostCharcardId int32 `protobuf:"varint,14,opt,name=host_charcard_id,json=hostCharcardId,proto3" json:"host_charcard_id,omitempty"`
	HostCardsetId  int32 `protobuf:"varint,15,opt,name=host_cardset_id,json=hostCardsetId,proto3" json:"host_cardset_id,omitempty"`
	HostCardlevel  int32 `protobuf:"varint,16,opt,name=host_cardlevel,json=hostCardlevel,proto3" json:"host_cardlevel,omitempty"`
	// duel-inst
	DuelCharcardId       int32    `protobuf:"varint,17,opt,name=duel_charcard_id,json=duelCharcardId,proto3" json:"duel_charcard_id,omitempty"`
	DuelCardsetId        int32    `protobuf:"varint,18,opt,name=duel_cardset_id,json=duelCardsetId,proto3" json:"duel_cardset_id,omitempty"`
	DuelCardlevel        int32    `protobuf:"varint,19,opt,name=duel_cardlevel,json=duelCardlevel,proto3" json:"duel_cardlevel,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Room) Reset()         { *m = Room{} }
func (m *Room) String() string { return proto.CompactTextString(m) }
func (*Room) ProtoMessage()    {}
func (*Room) Descriptor() ([]byte, []int) {
	return fileDescriptor_33c57e4bae7b9afd, []int{2}
}

func (m *Room) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Room.Unmarshal(m, b)
}
func (m *Room) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Room.Marshal(b, m, deterministic)
}
func (m *Room) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Room.Merge(m, src)
}
func (m *Room) XXX_Size() int {
	return xxx_messageInfo_Room.Size(m)
}
func (m *Room) XXX_DiscardUnknown() {
	xxx_messageInfo_Room.DiscardUnknown(m)
}

var xxx_messageInfo_Room proto.InternalMessageInfo

func (m *Room) GetId() string {
	if m != nil {
		return m.Id
	}
	return ""
}

func (m *Room) GetKey() string {
	if m != nil {
		return m.Key
	}
	return ""
}

func (m *Room) GetPassword() string {
	if m != nil {
		return m.Password
	}
	return ""
}

func (m *Room) GetHost() *RmUserInfo {
	if m != nil {
		return m.Host
	}
	return nil
}

func (m *Room) GetDueler() *RmUserInfo {
	if m != nil {
		return m.Dueler
	}
	return nil
}

func (m *Room) GetStatus() RoomStatus {
	if m != nil {
		return m.Status
	}
	return RoomStatus_ON_INIT
}

func (m *Room) GetTurns() int32 {
	if m != nil {
		return m.Turns
	}
	return 0
}

func (m *Room) GetCostLimitMax() int32 {
	if m != nil {
		return m.CostLimitMax
	}
	return 0
}

func (m *Room) GetCostLimitMin() int32 {
	if m != nil {
		return m.CostLimitMin
	}
	return 0
}

func (m *Room) GetCharCardLimitMax() *RmCharCardInfo {
	if m != nil {
		return m.CharCardLimitMax
	}
	return nil
}

func (m *Room) GetCharCardLimitMin() *RmCharCardInfo {
	if m != nil {
		return m.CharCardLimitMin
	}
	return nil
}

func (m *Room) GetCharCardNvn() int32 {
	if m != nil {
		return m.CharCardNvn
	}
	return 0
}

func (m *Room) GetHostCharcardId() int32 {
	if m != nil {
		return m.HostCharcardId
	}
	return 0
}

func (m *Room) GetHostCardsetId() int32 {
	if m != nil {
		return m.HostCardsetId
	}
	return 0
}

func (m *Room) GetHostCardlevel() int32 {
	if m != nil {
		return m.HostCardlevel
	}
	return 0
}

func (m *Room) GetDuelCharcardId() int32 {
	if m != nil {
		return m.DuelCharcardId
	}
	return 0
}

func (m *Room) GetDuelCardsetId() int32 {
	if m != nil {
		return m.DuelCardsetId
	}
	return 0
}

func (m *Room) GetDuelCardlevel() int32 {
	if m != nil {
		return m.DuelCardlevel
	}
	return 0
}

//*
//RmMsg :
//to pass the user message / stricker
type RoomMsg struct {
	Key                  string          `protobuf:"bytes,1,opt,name=key,proto3" json:"key,omitempty"`
	FromId               string          `protobuf:"bytes,2,opt,name=from_id,json=fromId,proto3" json:"from_id,omitempty"`
	FmName               string          `protobuf:"bytes,3,opt,name=fm_name,json=fmName,proto3" json:"fm_name,omitempty"`
	ToId                 string          `protobuf:"bytes,4,opt,name=to_id,json=toId,proto3" json:"to_id,omitempty"`
	ToName               string          `protobuf:"bytes,5,opt,name=to_name,json=toName,proto3" json:"to_name,omitempty"`
	Message              string          `protobuf:"bytes,6,opt,name=message,proto3" json:"message,omitempty"`
	MsgType              RoomMsg_MsgType `protobuf:"varint,7,opt,name=msg_type,json=msgType,proto3,enum=ULZProto.RoomMsg_MsgType" json:"msg_type,omitempty"`
	XXX_NoUnkeyedLiteral struct{}        `json:"-"`
	XXX_unrecognized     []byte          `json:"-"`
	XXX_sizecache        int32           `json:"-"`
}

func (m *RoomMsg) Reset()         { *m = RoomMsg{} }
func (m *RoomMsg) String() string { return proto.CompactTextString(m) }
func (*RoomMsg) ProtoMessage()    {}
func (*RoomMsg) Descriptor() ([]byte, []int) {
	return fileDescriptor_33c57e4bae7b9afd, []int{3}
}

func (m *RoomMsg) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_RoomMsg.Unmarshal(m, b)
}
func (m *RoomMsg) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_RoomMsg.Marshal(b, m, deterministic)
}
func (m *RoomMsg) XXX_Merge(src proto.Message) {
	xxx_messageInfo_RoomMsg.Merge(m, src)
}
func (m *RoomMsg) XXX_Size() int {
	return xxx_messageInfo_RoomMsg.Size(m)
}
func (m *RoomMsg) XXX_DiscardUnknown() {
	xxx_messageInfo_RoomMsg.DiscardUnknown(m)
}

var xxx_messageInfo_RoomMsg proto.InternalMessageInfo

func (m *RoomMsg) GetKey() string {
	if m != nil {
		return m.Key
	}
	return ""
}

func (m *RoomMsg) GetFromId() string {
	if m != nil {
		return m.FromId
	}
	return ""
}

func (m *RoomMsg) GetFmName() string {
	if m != nil {
		return m.FmName
	}
	return ""
}

func (m *RoomMsg) GetToId() string {
	if m != nil {
		return m.ToId
	}
	return ""
}

func (m *RoomMsg) GetToName() string {
	if m != nil {
		return m.ToName
	}
	return ""
}

func (m *RoomMsg) GetMessage() string {
	if m != nil {
		return m.Message
	}
	return ""
}

func (m *RoomMsg) GetMsgType() RoomMsg_MsgType {
	if m != nil {
		return m.MsgType
	}
	return RoomMsg_USER_TEXT
}

type RoomReq struct {
	Key                  string      `protobuf:"bytes,1,opt,name=key,proto3" json:"key,omitempty"`
	User                 *RmUserInfo `protobuf:"bytes,2,opt,name=user,proto3" json:"user,omitempty"`
	IsDuel               bool        `protobuf:"varint,3,opt,name=is_duel,json=isDuel,proto3" json:"is_duel,omitempty"`
	Password             string      `protobuf:"bytes,4,opt,name=password,proto3" json:"password,omitempty"`
	XXX_NoUnkeyedLiteral struct{}    `json:"-"`
	XXX_unrecognized     []byte      `json:"-"`
	XXX_sizecache        int32       `json:"-"`
}

func (m *RoomReq) Reset()         { *m = RoomReq{} }
func (m *RoomReq) String() string { return proto.CompactTextString(m) }
func (*RoomReq) ProtoMessage()    {}
func (*RoomReq) Descriptor() ([]byte, []int) {
	return fileDescriptor_33c57e4bae7b9afd, []int{4}
}

func (m *RoomReq) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_RoomReq.Unmarshal(m, b)
}
func (m *RoomReq) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_RoomReq.Marshal(b, m, deterministic)
}
func (m *RoomReq) XXX_Merge(src proto.Message) {
	xxx_messageInfo_RoomReq.Merge(m, src)
}
func (m *RoomReq) XXX_Size() int {
	return xxx_messageInfo_RoomReq.Size(m)
}
func (m *RoomReq) XXX_DiscardUnknown() {
	xxx_messageInfo_RoomReq.DiscardUnknown(m)
}

var xxx_messageInfo_RoomReq proto.InternalMessageInfo

func (m *RoomReq) GetKey() string {
	if m != nil {
		return m.Key
	}
	return ""
}

func (m *RoomReq) GetUser() *RmUserInfo {
	if m != nil {
		return m.User
	}
	return nil
}

func (m *RoomReq) GetIsDuel() bool {
	if m != nil {
		return m.IsDuel
	}
	return false
}

func (m *RoomReq) GetPassword() string {
	if m != nil {
		return m.Password
	}
	return ""
}

type RoomCreateReq struct {
	Key          string      `protobuf:"bytes,1,opt,name=key,proto3" json:"key,omitempty"`
	Host         *RmUserInfo `protobuf:"bytes,2,opt,name=host,proto3" json:"host,omitempty"`
	Password     string      `protobuf:"bytes,3,opt,name=password,proto3" json:"password,omitempty"`
	CostLimitMax int32       `protobuf:"varint,4,opt,name=cost_limit_max,json=costLimitMax,proto3" json:"cost_limit_max,omitempty"`
	CostLimitMin int32       `protobuf:"varint,5,opt,name=cost_limit_min,json=costLimitMin,proto3" json:"cost_limit_min,omitempty"`
	// 1vs1 or 3vs3
	CharCardNvn int32 `protobuf:"varint,6,opt,name=char_card_nvn,json=charCardNvn,proto3" json:"char_card_nvn,omitempty"`
	// Limitation for Charecter Card Cost
	CharCardLimitMax     *RmCharCardInfo `protobuf:"bytes,7,opt,name=char_card_limit_max,json=charCardLimitMax,proto3" json:"char_card_limit_max,omitempty"`
	CharCardLimitMin     *RmCharCardInfo `protobuf:"bytes,8,opt,name=char_card_limit_min,json=charCardLimitMin,proto3" json:"char_card_limit_min,omitempty"`
	XXX_NoUnkeyedLiteral struct{}        `json:"-"`
	XXX_unrecognized     []byte          `json:"-"`
	XXX_sizecache        int32           `json:"-"`
}

func (m *RoomCreateReq) Reset()         { *m = RoomCreateReq{} }
func (m *RoomCreateReq) String() string { return proto.CompactTextString(m) }
func (*RoomCreateReq) ProtoMessage()    {}
func (*RoomCreateReq) Descriptor() ([]byte, []int) {
	return fileDescriptor_33c57e4bae7b9afd, []int{5}
}

func (m *RoomCreateReq) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_RoomCreateReq.Unmarshal(m, b)
}
func (m *RoomCreateReq) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_RoomCreateReq.Marshal(b, m, deterministic)
}
func (m *RoomCreateReq) XXX_Merge(src proto.Message) {
	xxx_messageInfo_RoomCreateReq.Merge(m, src)
}
func (m *RoomCreateReq) XXX_Size() int {
	return xxx_messageInfo_RoomCreateReq.Size(m)
}
func (m *RoomCreateReq) XXX_DiscardUnknown() {
	xxx_messageInfo_RoomCreateReq.DiscardUnknown(m)
}

var xxx_messageInfo_RoomCreateReq proto.InternalMessageInfo

func (m *RoomCreateReq) GetKey() string {
	if m != nil {
		return m.Key
	}
	return ""
}

func (m *RoomCreateReq) GetHost() *RmUserInfo {
	if m != nil {
		return m.Host
	}
	return nil
}

func (m *RoomCreateReq) GetPassword() string {
	if m != nil {
		return m.Password
	}
	return ""
}

func (m *RoomCreateReq) GetCostLimitMax() int32 {
	if m != nil {
		return m.CostLimitMax
	}
	return 0
}

func (m *RoomCreateReq) GetCostLimitMin() int32 {
	if m != nil {
		return m.CostLimitMin
	}
	return 0
}

func (m *RoomCreateReq) GetCharCardNvn() int32 {
	if m != nil {
		return m.CharCardNvn
	}
	return 0
}

func (m *RoomCreateReq) GetCharCardLimitMax() *RmCharCardInfo {
	if m != nil {
		return m.CharCardLimitMax
	}
	return nil
}

func (m *RoomCreateReq) GetCharCardLimitMin() *RmCharCardInfo {
	if m != nil {
		return m.CharCardLimitMin
	}
	return nil
}

type RoomBroadcastInfo struct {
	Key                  string   `protobuf:"bytes,1,opt,name=key,proto3" json:"key,omitempty"`
	Ip                   string   `protobuf:"bytes,2,opt,name=ip,proto3" json:"ip,omitempty"`
	Port                 int32    `protobuf:"varint,3,opt,name=port,proto3" json:"port,omitempty"`
	Protocal             string   `protobuf:"bytes,4,opt,name=protocal,proto3" json:"protocal,omitempty"`
	Securl               []byte   `protobuf:"bytes,5,opt,name=securl,proto3" json:"securl,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *RoomBroadcastInfo) Reset()         { *m = RoomBroadcastInfo{} }
func (m *RoomBroadcastInfo) String() string { return proto.CompactTextString(m) }
func (*RoomBroadcastInfo) ProtoMessage()    {}
func (*RoomBroadcastInfo) Descriptor() ([]byte, []int) {
	return fileDescriptor_33c57e4bae7b9afd, []int{6}
}

func (m *RoomBroadcastInfo) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_RoomBroadcastInfo.Unmarshal(m, b)
}
func (m *RoomBroadcastInfo) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_RoomBroadcastInfo.Marshal(b, m, deterministic)
}
func (m *RoomBroadcastInfo) XXX_Merge(src proto.Message) {
	xxx_messageInfo_RoomBroadcastInfo.Merge(m, src)
}
func (m *RoomBroadcastInfo) XXX_Size() int {
	return xxx_messageInfo_RoomBroadcastInfo.Size(m)
}
func (m *RoomBroadcastInfo) XXX_DiscardUnknown() {
	xxx_messageInfo_RoomBroadcastInfo.DiscardUnknown(m)
}

var xxx_messageInfo_RoomBroadcastInfo proto.InternalMessageInfo

func (m *RoomBroadcastInfo) GetKey() string {
	if m != nil {
		return m.Key
	}
	return ""
}

func (m *RoomBroadcastInfo) GetIp() string {
	if m != nil {
		return m.Ip
	}
	return ""
}

func (m *RoomBroadcastInfo) GetPort() int32 {
	if m != nil {
		return m.Port
	}
	return 0
}

func (m *RoomBroadcastInfo) GetProtocal() string {
	if m != nil {
		return m.Protocal
	}
	return ""
}

func (m *RoomBroadcastInfo) GetSecurl() []byte {
	if m != nil {
		return m.Securl
	}
	return nil
}

type RoomUpdateCardReq struct {
	Key                  string                       `protobuf:"bytes,1,opt,name=key,proto3" json:"key,omitempty"`
	Side                 RoomUpdateCardReq_PlayerSide `protobuf:"varint,2,opt,name=side,proto3,enum=ULZProto.RoomUpdateCardReq_PlayerSide" json:"side,omitempty"`
	CharcardId           int32                        `protobuf:"varint,3,opt,name=charcard_id,json=charcardId,proto3" json:"charcard_id,omitempty"`
	CardsetId            int32                        `protobuf:"varint,4,opt,name=cardset_id,json=cardsetId,proto3" json:"cardset_id,omitempty"`
	Level                int32                        `protobuf:"varint,5,opt,name=level,proto3" json:"level,omitempty"`
	XXX_NoUnkeyedLiteral struct{}                     `json:"-"`
	XXX_unrecognized     []byte                       `json:"-"`
	XXX_sizecache        int32                        `json:"-"`
}

func (m *RoomUpdateCardReq) Reset()         { *m = RoomUpdateCardReq{} }
func (m *RoomUpdateCardReq) String() string { return proto.CompactTextString(m) }
func (*RoomUpdateCardReq) ProtoMessage()    {}
func (*RoomUpdateCardReq) Descriptor() ([]byte, []int) {
	return fileDescriptor_33c57e4bae7b9afd, []int{7}
}

func (m *RoomUpdateCardReq) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_RoomUpdateCardReq.Unmarshal(m, b)
}
func (m *RoomUpdateCardReq) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_RoomUpdateCardReq.Marshal(b, m, deterministic)
}
func (m *RoomUpdateCardReq) XXX_Merge(src proto.Message) {
	xxx_messageInfo_RoomUpdateCardReq.Merge(m, src)
}
func (m *RoomUpdateCardReq) XXX_Size() int {
	return xxx_messageInfo_RoomUpdateCardReq.Size(m)
}
func (m *RoomUpdateCardReq) XXX_DiscardUnknown() {
	xxx_messageInfo_RoomUpdateCardReq.DiscardUnknown(m)
}

var xxx_messageInfo_RoomUpdateCardReq proto.InternalMessageInfo

func (m *RoomUpdateCardReq) GetKey() string {
	if m != nil {
		return m.Key
	}
	return ""
}

func (m *RoomUpdateCardReq) GetSide() RoomUpdateCardReq_PlayerSide {
	if m != nil {
		return m.Side
	}
	return RoomUpdateCardReq_HOST
}

func (m *RoomUpdateCardReq) GetCharcardId() int32 {
	if m != nil {
		return m.CharcardId
	}
	return 0
}

func (m *RoomUpdateCardReq) GetCardsetId() int32 {
	if m != nil {
		return m.CardsetId
	}
	return 0
}

func (m *RoomUpdateCardReq) GetLevel() int32 {
	if m != nil {
		return m.Level
	}
	return 0
}

func init() {
	proto.RegisterEnum("ULZProto.RoomStatus", RoomStatus_name, RoomStatus_value)
	proto.RegisterEnum("ULZProto.RoomMsg_MsgType", RoomMsg_MsgType_name, RoomMsg_MsgType_value)
	proto.RegisterEnum("ULZProto.RoomUpdateCardReq_PlayerSide", RoomUpdateCardReq_PlayerSide_name, RoomUpdateCardReq_PlayerSide_value)
	proto.RegisterType((*RmCharCardInfo)(nil), "ULZProto.RmCharCardInfo")
	proto.RegisterType((*RmUserInfo)(nil), "ULZProto.RmUserInfo")
	proto.RegisterType((*Room)(nil), "ULZProto.Room")
	proto.RegisterType((*RoomMsg)(nil), "ULZProto.RoomMsg")
	proto.RegisterType((*RoomReq)(nil), "ULZProto.RoomReq")
	proto.RegisterType((*RoomCreateReq)(nil), "ULZProto.RoomCreateReq")
	proto.RegisterType((*RoomBroadcastInfo)(nil), "ULZProto.RoomBroadcastInfo")
	proto.RegisterType((*RoomUpdateCardReq)(nil), "ULZProto.RoomUpdateCardReq")
}

func init() { proto.RegisterFile("message.proto", fileDescriptor_33c57e4bae7b9afd) }

var fileDescriptor_33c57e4bae7b9afd = []byte{
	// 978 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0xac, 0x55, 0xdd, 0x8e, 0xe3, 0x44,
	0x13, 0xfd, 0xe2, 0x71, 0x1c, 0xa7, 0x32, 0xc9, 0x78, 0x7a, 0x56, 0xdf, 0x7a, 0x41, 0x88, 0x95,
	0x05, 0xab, 0x08, 0xa1, 0x5c, 0x2c, 0x5c, 0x71, 0x37, 0x3f, 0x01, 0x2c, 0x26, 0xce, 0xa8, 0x93,
	0x68, 0xd9, 0x95, 0x90, 0xd5, 0xd8, 0xbd, 0x19, 0x6b, 0x62, 0x77, 0xe8, 0x76, 0x86, 0x1d, 0x24,
	0x1e, 0x81, 0x17, 0xd9, 0xe7, 0xe1, 0x8e, 0x27, 0xe0, 0x2d, 0x50, 0x57, 0x3b, 0x3f, 0xde, 0xcc,
	0x00, 0x2b, 0x71, 0xd7, 0x75, 0xfa, 0xb8, 0x4f, 0x75, 0xb9, 0xea, 0x34, 0x74, 0x73, 0xae, 0x14,
	0x9b, 0xf3, 0xc1, 0x52, 0x8a, 0x52, 0x10, 0x77, 0x76, 0xf9, 0xea, 0x4a, 0xaf, 0x82, 0x39, 0xf4,
	0x68, 0x7e, 0x7e, 0xcd, 0xe4, 0x39, 0x93, 0x69, 0x58, 0xbc, 0x16, 0xe4, 0x31, 0xb4, 0x12, 0x26,
	0xd3, 0x38, 0x4b, 0xfd, 0xc6, 0xd3, 0x46, 0xbf, 0x49, 0x1d, 0x1d, 0x86, 0x29, 0x79, 0x04, 0xcd,
	0x05, 0xbf, 0xe5, 0x0b, 0xdf, 0x42, 0xd8, 0x04, 0x84, 0x80, 0x2d, 0x99, 0xe4, 0xfe, 0x01, 0x82,
	0xb8, 0xd6, 0x58, 0x22, 0x54, 0xe9, 0xdb, 0x06, 0xd3, 0xeb, 0xe0, 0xb7, 0x06, 0x00, 0xcd, 0x67,
	0x8a, 0x4b, 0x54, 0xe9, 0x81, 0x55, 0x09, 0xb4, 0xa9, 0x95, 0xa5, 0xfa, 0x93, 0x82, 0xe5, 0x1c,
	0xcf, 0x6e, 0x53, 0x5c, 0x6f, 0x05, 0x0f, 0x76, 0x05, 0x3f, 0x84, 0x36, 0xbb, 0x65, 0x65, 0x9c,
	0x25, 0xa2, 0x40, 0x85, 0x36, 0x75, 0x35, 0x10, 0x26, 0xa2, 0xd0, 0x9f, 0x94, 0x59, 0xb9, 0xe0,
	0x7e, 0x13, 0x37, 0x4c, 0x60, 0x72, 0x2c, 0x6e, 0x7c, 0x67, 0x9d, 0x63, 0x71, 0x13, 0xfc, 0xde,
	0x04, 0x9b, 0x0a, 0x91, 0xef, 0x65, 0xe2, 0xc1, 0xc1, 0x0d, 0xbf, 0xab, 0x12, 0xd1, 0x4b, 0xf2,
	0x01, 0xb8, 0x4b, 0xa6, 0xd4, 0xcf, 0x42, 0xa6, 0x98, 0x4a, 0x9b, 0x6e, 0x62, 0xd2, 0x07, 0xfb,
	0x7a, 0x7d, 0xd5, 0xce, 0xf3, 0x47, 0x83, 0x75, 0x61, 0x07, 0xdb, 0xbb, 0x52, 0x64, 0x90, 0xcf,
	0xc1, 0x49, 0x57, 0x7c, 0xc1, 0x25, 0xe6, 0xf6, 0x10, 0xb7, 0xe2, 0x68, 0xb6, 0x2a, 0x59, 0xb9,
	0x52, 0x7e, 0xeb, 0x69, 0xa3, 0xdf, 0xab, 0xb1, 0x85, 0xc8, 0x27, 0xb8, 0x47, 0x2b, 0x0e, 0x5e,
	0x7b, 0x25, 0x0b, 0xe5, 0xbb, 0xa6, 0x52, 0x18, 0x90, 0x4f, 0xa0, 0xa7, 0x4b, 0x1f, 0x2f, 0xb2,
	0x3c, 0x2b, 0xe3, 0x9c, 0xbd, 0xf1, 0xdb, 0xb8, 0x7d, 0xa8, 0xd1, 0x4b, 0x0d, 0x8e, 0xd8, 0x9b,
	0x77, 0x59, 0x59, 0xe1, 0xc3, 0xbb, 0xac, 0xac, 0x20, 0xdf, 0xc0, 0x49, 0x72, 0xcd, 0x64, 0x8c,
	0xad, 0xb1, 0x3d, 0xb0, 0x83, 0x57, 0xf1, 0x77, 0xaf, 0xb2, 0xdb, 0x4c, 0xd4, 0x4b, 0xaa, 0x68,
	0x23, 0x77, 0xdf, 0x41, 0x59, 0xe1, 0x1f, 0xbe, 0xdf, 0x41, 0x59, 0x41, 0x02, 0xe8, 0x6e, 0x0f,
	0x2a, 0x6e, 0x0b, 0xbf, 0x8b, 0x69, 0x77, 0xd6, 0xc4, 0xe8, 0xb6, 0x20, 0x7d, 0xf0, 0x74, 0xed,
	0x63, 0x8d, 0xad, 0x9b, 0xba, 0x87, 0xb4, 0x9e, 0xc6, 0xcf, 0x2b, 0x38, 0x4c, 0xc9, 0x33, 0x38,
	0x32, 0x4c, 0x26, 0x53, 0xc5, 0x4b, 0x4d, 0x3c, 0x42, 0x62, 0x17, 0x89, 0x06, 0x0d, 0x53, 0xf2,
	0x29, 0xf4, 0x36, 0x3c, 0xd3, 0x9c, 0x5e, 0x9d, 0x66, 0x9a, 0xb4, 0x0f, 0x9e, 0xfe, 0x91, 0x35,
	0xe1, 0x63, 0x23, 0xac, 0xf1, 0xba, 0xb0, 0x61, 0x6e, 0x85, 0x89, 0x39, 0x11, 0x89, 0xbb, 0xc2,
	0x1b, 0x9e, 0x11, 0x3e, 0xa9, 0xd3, 0x10, 0x0c, 0xde, 0x5a, 0xd0, 0xd2, 0x0d, 0x32, 0x52, 0xf3,
	0x75, 0x27, 0x37, 0xb6, 0x9d, 0xfc, 0x18, 0x5a, 0xaf, 0xa5, 0xc8, 0xb5, 0x88, 0xe9, 0x6f, 0x47,
	0x87, 0x61, 0x8a, 0x1b, 0x79, 0x8c, 0x13, 0x78, 0x50, 0x6d, 0xe4, 0x91, 0x9e, 0xc1, 0x13, 0x68,
	0x96, 0x42, 0xf3, 0xcd, 0xa4, 0xd9, 0xa5, 0x30, 0xec, 0x52, 0x18, 0xb6, 0x99, 0x33, 0xa7, 0x14,
	0xc8, 0xf6, 0xa1, 0x55, 0x19, 0x0d, 0xce, 0x5a, 0x9b, 0xae, 0x43, 0xf2, 0x25, 0xb8, 0xb9, 0x9a,
	0xc7, 0xe5, 0xdd, 0x92, 0x57, 0x1d, 0xfd, 0xa4, 0xde, 0xd1, 0x23, 0x35, 0x1f, 0x8c, 0xd4, 0x7c,
	0x7a, 0xb7, 0xe4, 0xb4, 0x95, 0x9b, 0x45, 0xf0, 0x03, 0xb4, 0x2a, 0x8c, 0x74, 0xa1, 0x3d, 0x9b,
	0x0c, 0x69, 0x3c, 0x1d, 0x7e, 0x3f, 0xf5, 0xfe, 0x47, 0x8e, 0xa1, 0x8b, 0xe1, 0x64, 0x4a, 0xc3,
	0xf3, 0xef, 0x86, 0xd4, 0x6b, 0x90, 0x23, 0xe8, 0x4c, 0x5e, 0x4e, 0xa6, 0xc3, 0x51, 0x1c, 0x46,
	0x5f, 0x8f, 0x3d, 0x6b, 0x07, 0x78, 0x71, 0x4a, 0x23, 0xef, 0x80, 0xf4, 0x00, 0x2a, 0x60, 0x48,
	0xa9, 0x67, 0x07, 0xbf, 0x98, 0x5a, 0x51, 0xfe, 0xd3, 0x3d, 0xb5, 0xea, 0x83, 0xbd, 0x52, 0x5c,
	0x62, 0xa1, 0x1e, 0x9c, 0x6c, 0xcd, 0xd0, 0xe5, 0xc8, 0x54, 0xac, 0xff, 0x03, 0x16, 0xcf, 0xa5,
	0x4e, 0xa6, 0x2e, 0x56, 0x7c, 0x51, 0x33, 0x0e, 0xbb, 0x6e, 0x1c, 0xc1, 0x9f, 0x16, 0x74, 0xb5,
	0xf8, 0xb9, 0xe4, 0xac, 0xe4, 0x0f, 0xa6, 0x80, 0xe6, 0x62, 0xfd, 0xa3, 0xb9, 0xfc, 0x9d, 0x45,
	0xed, 0xdb, 0x80, 0xfd, 0xaf, 0x6c, 0xa0, 0x79, 0x8f, 0x0d, 0xec, 0x0d, 0x9d, 0xb3, 0x3f, 0x74,
	0x0f, 0x58, 0x45, 0xeb, 0xbf, 0xb2, 0x0a, 0xf7, 0x7d, 0xad, 0x22, 0xf8, 0x15, 0x8e, 0x75, 0xa9,
	0xcf, 0xa4, 0x60, 0x69, 0xc2, 0x54, 0x89, 0x2f, 0xd0, 0x7e, 0xb9, 0xf5, 0x4b, 0xb0, 0xac, 0x06,
	0xc3, 0xca, 0x96, 0xfa, 0xd9, 0x58, 0x0a, 0x59, 0xae, 0x9f, 0x36, 0xbd, 0xc6, 0x42, 0x6b, 0xd1,
	0x84, 0x2d, 0x36, 0xbf, 0xb4, 0x8a, 0xc9, 0xff, 0xc1, 0x51, 0x3c, 0x59, 0xc9, 0x05, 0x96, 0xee,
	0x90, 0x56, 0x51, 0xf0, 0x47, 0xc3, 0xe8, 0xcf, 0x96, 0x29, 0x2b, 0xb9, 0xce, 0xec, 0xfe, 0xdf,
	0xfd, 0x15, 0xd8, 0x2a, 0x4b, 0xcd, 0x1b, 0xd8, 0x7b, 0xfe, 0xac, 0x3e, 0x1f, 0xb5, 0x8f, 0x07,
	0x57, 0x0b, 0x76, 0xc7, 0xe5, 0x24, 0x4b, 0x39, 0xc5, 0x6f, 0xc8, 0xc7, 0xd0, 0xd9, 0xf5, 0x1a,
	0x93, 0x32, 0x24, 0x5b, 0x9f, 0xf9, 0x08, 0x60, 0xc7, 0x62, 0x4c, 0x07, 0xb4, 0x93, 0x8d, 0xbd,
	0x6c, 0xde, 0xda, 0xe6, 0xce, 0x5b, 0x1b, 0x04, 0x00, 0x5b, 0x25, 0xe2, 0x82, 0xfd, 0xed, 0x78,
	0xa2, 0xa7, 0x0f, 0xc0, 0xb9, 0x98, 0x0d, 0x2f, 0xf5, 0xd8, 0x7d, 0x76, 0x05, 0xb0, 0x7d, 0x91,
	0x48, 0x07, 0x5a, 0xe3, 0x28, 0x0e, 0xa3, 0x50, 0xd3, 0x4c, 0xf0, 0xe2, 0x34, 0x9c, 0x7a, 0x0d,
	0x72, 0x08, 0xee, 0x38, 0x8a, 0x27, 0xd3, 0x53, 0x3a, 0xf5, 0x2c, 0x7d, 0xc2, 0x38, 0x8a, 0x87,
	0xd1, 0x85, 0x19, 0xcb, 0x71, 0x14, 0x5f, 0x0c, 0x27, 0x53, 0x3a, 0x7e, 0xe9, 0xd9, 0x67, 0x67,
	0xf0, 0x24, 0x13, 0x83, 0xb9, 0x5c, 0x26, 0xba, 0x04, 0xa7, 0x4a, 0xf1, 0x72, 0x80, 0x85, 0x18,
	0x89, 0xf4, 0xcc, 0x5d, 0x43, 0x57, 0x8d, 0x57, 0x4d, 0x2c, 0xfd, 0x5b, 0xeb, 0x78, 0x8f, 0xf6,
	0xa3, 0x83, 0x5b, 0x5f, 0xfc, 0x15, 0x00, 0x00, 0xff, 0xff, 0xfd, 0x8f, 0x58, 0x14, 0xf9, 0x08,
	0x00, 0x00,
}
