// Code generated by protoc-gen-go. DO NOT EDIT.
// source: message.proto

package proto

import (
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

type RoomStatus int32

const (
	RoomStatus_ON_START     RoomStatus = 0
	RoomStatus_ON_WAIT      RoomStatus = 1
	RoomStatus_ON_HOST_TURN RoomStatus = 2
	RoomStatus_ON_DUEL_TURN RoomStatus = 3
	RoomStatus_ON_END       RoomStatus = 4
)

var RoomStatus_name = map[int32]string{
	0: "ON_START",
	1: "ON_WAIT",
	2: "ON_HOST_TURN",
	3: "ON_DUEL_TURN",
	4: "ON_END",
}

var RoomStatus_value = map[string]int32{
	"ON_START":     0,
	"ON_WAIT":      1,
	"ON_HOST_TURN": 2,
	"ON_DUEL_TURN": 3,
	"ON_END":       4,
}

func (x RoomStatus) String() string {
	return proto.EnumName(RoomStatus_name, int32(x))
}

func (RoomStatus) EnumDescriptor() ([]byte, []int) {
	return fileDescriptor_33c57e4bae7b9afd, []int{0}
}

type RoomMsg_MsgType int32

const (
	RoomMsg_USER_TEXT     RoomMsg_MsgType = 0
	RoomMsg_USER_STRICKER RoomMsg_MsgType = 1
	RoomMsg_SYSTEM_INFO   RoomMsg_MsgType = 2
	RoomMsg_SYSTEM_WARN   RoomMsg_MsgType = 3
	RoomMsg_SYSTEM_ERR    RoomMsg_MsgType = 4
)

var RoomMsg_MsgType_name = map[int32]string{
	0: "USER_TEXT",
	1: "USER_STRICKER",
	2: "SYSTEM_INFO",
	3: "SYSTEM_WARN",
	4: "SYSTEM_ERR",
}

var RoomMsg_MsgType_value = map[string]int32{
	"USER_TEXT":     0,
	"USER_STRICKER": 1,
	"SYSTEM_INFO":   2,
	"SYSTEM_WARN":   3,
	"SYSTEM_ERR":    4,
}

func (x RoomMsg_MsgType) String() string {
	return proto.EnumName(RoomMsg_MsgType_name, int32(x))
}

func (RoomMsg_MsgType) EnumDescriptor() ([]byte, []int) {
	return fileDescriptor_33c57e4bae7b9afd, []int{4, 0}
}

// RmCharCardInfo
//      Basic Character Card Infomation
type RmCharCardInfo struct {
	CardId               int32    `protobuf:"varint,1,opt,name=card_id,json=cardId,proto3" json:"card_id,omitempty"`
	Level                int32    `protobuf:"varint,2,opt,name=level,proto3" json:"level,omitempty"`
	Rare                 int32    `protobuf:"varint,3,opt,name=rare,proto3" json:"rare,omitempty"`
	Cost                 int32    `protobuf:"varint,4,opt,name=cost,proto3" json:"cost,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *RmCharCardInfo) Reset()         { *m = RmCharCardInfo{} }
func (m *RmCharCardInfo) String() string { return proto.CompactTextString(m) }
func (*RmCharCardInfo) ProtoMessage()    {}
func (*RmCharCardInfo) Descriptor() ([]byte, []int) {
	return fileDescriptor_33c57e4bae7b9afd, []int{0}
}

func (m *RmCharCardInfo) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_RmCharCardInfo.Unmarshal(m, b)
}
func (m *RmCharCardInfo) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_RmCharCardInfo.Marshal(b, m, deterministic)
}
func (m *RmCharCardInfo) XXX_Merge(src proto.Message) {
	xxx_messageInfo_RmCharCardInfo.Merge(m, src)
}
func (m *RmCharCardInfo) XXX_Size() int {
	return xxx_messageInfo_RmCharCardInfo.Size(m)
}
func (m *RmCharCardInfo) XXX_DiscardUnknown() {
	xxx_messageInfo_RmCharCardInfo.DiscardUnknown(m)
}

var xxx_messageInfo_RmCharCardInfo proto.InternalMessageInfo

func (m *RmCharCardInfo) GetCardId() int32 {
	if m != nil {
		return m.CardId
	}
	return 0
}

func (m *RmCharCardInfo) GetLevel() int32 {
	if m != nil {
		return m.Level
	}
	return 0
}

func (m *RmCharCardInfo) GetRare() int32 {
	if m != nil {
		return m.Rare
	}
	return 0
}

func (m *RmCharCardInfo) GetCost() int32 {
	if m != nil {
		return m.Cost
	}
	return 0
}

//*
//RmUserInfo :
//User basic Information for room info displaying
type RmUserInfo struct {
	Id                   string   `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Name                 string   `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	Level                int32    `protobuf:"varint,3,opt,name=level,proto3" json:"level,omitempty"`
	AvatIcon             string   `protobuf:"bytes,4,opt,name=avat_icon,json=avatIcon,proto3" json:"avat_icon,omitempty"`
	Title                string   `protobuf:"bytes,5,opt,name=title,proto3" json:"title,omitempty"`
	Rank                 int32    `protobuf:"varint,6,opt,name=rank,proto3" json:"rank,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *RmUserInfo) Reset()         { *m = RmUserInfo{} }
func (m *RmUserInfo) String() string { return proto.CompactTextString(m) }
func (*RmUserInfo) ProtoMessage()    {}
func (*RmUserInfo) Descriptor() ([]byte, []int) {
	return fileDescriptor_33c57e4bae7b9afd, []int{1}
}

func (m *RmUserInfo) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_RmUserInfo.Unmarshal(m, b)
}
func (m *RmUserInfo) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_RmUserInfo.Marshal(b, m, deterministic)
}
func (m *RmUserInfo) XXX_Merge(src proto.Message) {
	xxx_messageInfo_RmUserInfo.Merge(m, src)
}
func (m *RmUserInfo) XXX_Size() int {
	return xxx_messageInfo_RmUserInfo.Size(m)
}
func (m *RmUserInfo) XXX_DiscardUnknown() {
	xxx_messageInfo_RmUserInfo.DiscardUnknown(m)
}

var xxx_messageInfo_RmUserInfo proto.InternalMessageInfo

func (m *RmUserInfo) GetId() string {
	if m != nil {
		return m.Id
	}
	return ""
}

func (m *RmUserInfo) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

func (m *RmUserInfo) GetLevel() int32 {
	if m != nil {
		return m.Level
	}
	return 0
}

func (m *RmUserInfo) GetAvatIcon() string {
	if m != nil {
		return m.AvatIcon
	}
	return ""
}

func (m *RmUserInfo) GetTitle() string {
	if m != nil {
		return m.Title
	}
	return ""
}

func (m *RmUserInfo) GetRank() int32 {
	if m != nil {
		return m.Rank
	}
	return 0
}

//*
//Room :
//Room Detail Information
type Room struct {
	// Room-id the id
	Id string `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	// Room-Key the id
	Key string `protobuf:"bytes,2,opt,name=key,proto3" json:"key,omitempty"`
	// Room Password
	Password string `protobuf:"bytes,3,opt,name=password,proto3" json:"password,omitempty"`
	// User-info for room-host player
	Host *RmUserInfo `protobuf:"bytes,4,opt,name=host,proto3" json:"host,omitempty"`
	// User-info for dueler-player
	Dueler *RmUserInfo `protobuf:"bytes,5,opt,name=dueler,proto3" json:"dueler,omitempty"`
	// Rooms Status
	Status RoomStatus `protobuf:"varint,7,opt,name=status,proto3,enum=ULZProto.RoomStatus" json:"status,omitempty"`
	// Turns number of Game Duel
	Turns int32 `protobuf:"varint,8,opt,name=turns,proto3" json:"turns,omitempty"`
	// Limitation for total Card-Deck
	CostLimitMax int32 `protobuf:"varint,9,opt,name=cost_limit_max,json=costLimitMax,proto3" json:"cost_limit_max,omitempty"`
	CostLimitMin int32 `protobuf:"varint,10,opt,name=cost_limit_min,json=costLimitMin,proto3" json:"cost_limit_min,omitempty"`
	// Limitation for Charecter Card Cost
	CharCardLimitMax *RmCharCardInfo `protobuf:"bytes,11,opt,name=char_card_limit_max,json=charCardLimitMax,proto3" json:"char_card_limit_max,omitempty"`
	CharCardLimitMin *RmCharCardInfo `protobuf:"bytes,12,opt,name=char_card_limit_min,json=charCardLimitMin,proto3" json:"char_card_limit_min,omitempty"`
	// 1vs1 or 3vs3
	CharCardNvn          int32    `protobuf:"varint,13,opt,name=char_card_nvn,json=charCardNvn,proto3" json:"char_card_nvn,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Room) Reset()         { *m = Room{} }
func (m *Room) String() string { return proto.CompactTextString(m) }
func (*Room) ProtoMessage()    {}
func (*Room) Descriptor() ([]byte, []int) {
	return fileDescriptor_33c57e4bae7b9afd, []int{2}
}

func (m *Room) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Room.Unmarshal(m, b)
}
func (m *Room) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Room.Marshal(b, m, deterministic)
}
func (m *Room) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Room.Merge(m, src)
}
func (m *Room) XXX_Size() int {
	return xxx_messageInfo_Room.Size(m)
}
func (m *Room) XXX_DiscardUnknown() {
	xxx_messageInfo_Room.DiscardUnknown(m)
}

var xxx_messageInfo_Room proto.InternalMessageInfo

func (m *Room) GetId() string {
	if m != nil {
		return m.Id
	}
	return ""
}

func (m *Room) GetKey() string {
	if m != nil {
		return m.Key
	}
	return ""
}

func (m *Room) GetPassword() string {
	if m != nil {
		return m.Password
	}
	return ""
}

func (m *Room) GetHost() *RmUserInfo {
	if m != nil {
		return m.Host
	}
	return nil
}

func (m *Room) GetDueler() *RmUserInfo {
	if m != nil {
		return m.Dueler
	}
	return nil
}

func (m *Room) GetStatus() RoomStatus {
	if m != nil {
		return m.Status
	}
	return RoomStatus_ON_START
}

func (m *Room) GetTurns() int32 {
	if m != nil {
		return m.Turns
	}
	return 0
}

func (m *Room) GetCostLimitMax() int32 {
	if m != nil {
		return m.CostLimitMax
	}
	return 0
}

func (m *Room) GetCostLimitMin() int32 {
	if m != nil {
		return m.CostLimitMin
	}
	return 0
}

func (m *Room) GetCharCardLimitMax() *RmCharCardInfo {
	if m != nil {
		return m.CharCardLimitMax
	}
	return nil
}

func (m *Room) GetCharCardLimitMin() *RmCharCardInfo {
	if m != nil {
		return m.CharCardLimitMin
	}
	return nil
}

func (m *Room) GetCharCardNvn() int32 {
	if m != nil {
		return m.CharCardNvn
	}
	return 0
}

//*
//RoomSH :
//Room Short hand
//for RoomList quick load for the listing
type RoomSH struct {
	// Room-Key the id
	Key string `protobuf:"bytes,1,opt,name=key,proto3" json:"key,omitempty"`
	// User-id for room-host player
	HostName             string     `protobuf:"bytes,2,opt,name=host_name,json=hostName,proto3" json:"host_name,omitempty"`
	HostLv               int32      `protobuf:"varint,3,opt,name=host_lv,json=hostLv,proto3" json:"host_lv,omitempty"`
	DuelerName           string     `protobuf:"bytes,4,opt,name=dueler_name,json=duelerName,proto3" json:"dueler_name,omitempty"`
	DuelerLv             int32      `protobuf:"varint,5,opt,name=dueler_lv,json=duelerLv,proto3" json:"dueler_lv,omitempty"`
	Status               RoomStatus `protobuf:"varint,6,opt,name=status,proto3,enum=ULZProto.RoomStatus" json:"status,omitempty"`
	Turns                int32      `protobuf:"varint,7,opt,name=turns,proto3" json:"turns,omitempty"`
	XXX_NoUnkeyedLiteral struct{}   `json:"-"`
	XXX_unrecognized     []byte     `json:"-"`
	XXX_sizecache        int32      `json:"-"`
}

func (m *RoomSH) Reset()         { *m = RoomSH{} }
func (m *RoomSH) String() string { return proto.CompactTextString(m) }
func (*RoomSH) ProtoMessage()    {}
func (*RoomSH) Descriptor() ([]byte, []int) {
	return fileDescriptor_33c57e4bae7b9afd, []int{3}
}

func (m *RoomSH) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_RoomSH.Unmarshal(m, b)
}
func (m *RoomSH) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_RoomSH.Marshal(b, m, deterministic)
}
func (m *RoomSH) XXX_Merge(src proto.Message) {
	xxx_messageInfo_RoomSH.Merge(m, src)
}
func (m *RoomSH) XXX_Size() int {
	return xxx_messageInfo_RoomSH.Size(m)
}
func (m *RoomSH) XXX_DiscardUnknown() {
	xxx_messageInfo_RoomSH.DiscardUnknown(m)
}

var xxx_messageInfo_RoomSH proto.InternalMessageInfo

func (m *RoomSH) GetKey() string {
	if m != nil {
		return m.Key
	}
	return ""
}

func (m *RoomSH) GetHostName() string {
	if m != nil {
		return m.HostName
	}
	return ""
}

func (m *RoomSH) GetHostLv() int32 {
	if m != nil {
		return m.HostLv
	}
	return 0
}

func (m *RoomSH) GetDuelerName() string {
	if m != nil {
		return m.DuelerName
	}
	return ""
}

func (m *RoomSH) GetDuelerLv() int32 {
	if m != nil {
		return m.DuelerLv
	}
	return 0
}

func (m *RoomSH) GetStatus() RoomStatus {
	if m != nil {
		return m.Status
	}
	return RoomStatus_ON_START
}

func (m *RoomSH) GetTurns() int32 {
	if m != nil {
		return m.Turns
	}
	return 0
}

//*
//RmMsg :
//to pass the user message / stricker
type RoomMsg struct {
	Key                  string          `protobuf:"bytes,1,opt,name=key,proto3" json:"key,omitempty"`
	FormId               string          `protobuf:"bytes,2,opt,name=form_id,json=formId,proto3" json:"form_id,omitempty"`
	ToId                 string          `protobuf:"bytes,3,opt,name=to_id,json=toId,proto3" json:"to_id,omitempty"`
	Message              string          `protobuf:"bytes,4,opt,name=message,proto3" json:"message,omitempty"`
	MsgType              RoomMsg_MsgType `protobuf:"varint,5,opt,name=msg_type,json=msgType,proto3,enum=ULZProto.RoomMsg_MsgType" json:"msg_type,omitempty"`
	XXX_NoUnkeyedLiteral struct{}        `json:"-"`
	XXX_unrecognized     []byte          `json:"-"`
	XXX_sizecache        int32           `json:"-"`
}

func (m *RoomMsg) Reset()         { *m = RoomMsg{} }
func (m *RoomMsg) String() string { return proto.CompactTextString(m) }
func (*RoomMsg) ProtoMessage()    {}
func (*RoomMsg) Descriptor() ([]byte, []int) {
	return fileDescriptor_33c57e4bae7b9afd, []int{4}
}

func (m *RoomMsg) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_RoomMsg.Unmarshal(m, b)
}
func (m *RoomMsg) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_RoomMsg.Marshal(b, m, deterministic)
}
func (m *RoomMsg) XXX_Merge(src proto.Message) {
	xxx_messageInfo_RoomMsg.Merge(m, src)
}
func (m *RoomMsg) XXX_Size() int {
	return xxx_messageInfo_RoomMsg.Size(m)
}
func (m *RoomMsg) XXX_DiscardUnknown() {
	xxx_messageInfo_RoomMsg.DiscardUnknown(m)
}

var xxx_messageInfo_RoomMsg proto.InternalMessageInfo

func (m *RoomMsg) GetKey() string {
	if m != nil {
		return m.Key
	}
	return ""
}

func (m *RoomMsg) GetFormId() string {
	if m != nil {
		return m.FormId
	}
	return ""
}

func (m *RoomMsg) GetToId() string {
	if m != nil {
		return m.ToId
	}
	return ""
}

func (m *RoomMsg) GetMessage() string {
	if m != nil {
		return m.Message
	}
	return ""
}

func (m *RoomMsg) GetMsgType() RoomMsg_MsgType {
	if m != nil {
		return m.MsgType
	}
	return RoomMsg_USER_TEXT
}

type RoomReq struct {
	RoomKey              string   `protobuf:"bytes,1,opt,name=room_key,json=roomKey,proto3" json:"room_key,omitempty"`
	UserId               string   `protobuf:"bytes,2,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *RoomReq) Reset()         { *m = RoomReq{} }
func (m *RoomReq) String() string { return proto.CompactTextString(m) }
func (*RoomReq) ProtoMessage()    {}
func (*RoomReq) Descriptor() ([]byte, []int) {
	return fileDescriptor_33c57e4bae7b9afd, []int{5}
}

func (m *RoomReq) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_RoomReq.Unmarshal(m, b)
}
func (m *RoomReq) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_RoomReq.Marshal(b, m, deterministic)
}
func (m *RoomReq) XXX_Merge(src proto.Message) {
	xxx_messageInfo_RoomReq.Merge(m, src)
}
func (m *RoomReq) XXX_Size() int {
	return xxx_messageInfo_RoomReq.Size(m)
}
func (m *RoomReq) XXX_DiscardUnknown() {
	xxx_messageInfo_RoomReq.DiscardUnknown(m)
}

var xxx_messageInfo_RoomReq proto.InternalMessageInfo

func (m *RoomReq) GetRoomKey() string {
	if m != nil {
		return m.RoomKey
	}
	return ""
}

func (m *RoomReq) GetUserId() string {
	if m != nil {
		return m.UserId
	}
	return ""
}

type RoomCreateReq struct {
	Host         *RmUserInfo `protobuf:"bytes,1,opt,name=host,proto3" json:"host,omitempty"`
	CostLimitMax int32       `protobuf:"varint,2,opt,name=cost_limit_max,json=costLimitMax,proto3" json:"cost_limit_max,omitempty"`
	CostLimitMin int32       `protobuf:"varint,3,opt,name=cost_limit_min,json=costLimitMin,proto3" json:"cost_limit_min,omitempty"`
	// 1vs1 or 3vs3
	CharCardNvn int32 `protobuf:"varint,4,opt,name=char_card_nvn,json=charCardNvn,proto3" json:"char_card_nvn,omitempty"`
	// Limitation for Charecter Card Cost
	CharCardLimitMax     *RmCharCardInfo `protobuf:"bytes,5,opt,name=char_card_limit_max,json=charCardLimitMax,proto3" json:"char_card_limit_max,omitempty"`
	CharCardLimitMin     *RmCharCardInfo `protobuf:"bytes,6,opt,name=char_card_limit_min,json=charCardLimitMin,proto3" json:"char_card_limit_min,omitempty"`
	XXX_NoUnkeyedLiteral struct{}        `json:"-"`
	XXX_unrecognized     []byte          `json:"-"`
	XXX_sizecache        int32           `json:"-"`
}

func (m *RoomCreateReq) Reset()         { *m = RoomCreateReq{} }
func (m *RoomCreateReq) String() string { return proto.CompactTextString(m) }
func (*RoomCreateReq) ProtoMessage()    {}
func (*RoomCreateReq) Descriptor() ([]byte, []int) {
	return fileDescriptor_33c57e4bae7b9afd, []int{6}
}

func (m *RoomCreateReq) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_RoomCreateReq.Unmarshal(m, b)
}
func (m *RoomCreateReq) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_RoomCreateReq.Marshal(b, m, deterministic)
}
func (m *RoomCreateReq) XXX_Merge(src proto.Message) {
	xxx_messageInfo_RoomCreateReq.Merge(m, src)
}
func (m *RoomCreateReq) XXX_Size() int {
	return xxx_messageInfo_RoomCreateReq.Size(m)
}
func (m *RoomCreateReq) XXX_DiscardUnknown() {
	xxx_messageInfo_RoomCreateReq.DiscardUnknown(m)
}

var xxx_messageInfo_RoomCreateReq proto.InternalMessageInfo

func (m *RoomCreateReq) GetHost() *RmUserInfo {
	if m != nil {
		return m.Host
	}
	return nil
}

func (m *RoomCreateReq) GetCostLimitMax() int32 {
	if m != nil {
		return m.CostLimitMax
	}
	return 0
}

func (m *RoomCreateReq) GetCostLimitMin() int32 {
	if m != nil {
		return m.CostLimitMin
	}
	return 0
}

func (m *RoomCreateReq) GetCharCardNvn() int32 {
	if m != nil {
		return m.CharCardNvn
	}
	return 0
}

func (m *RoomCreateReq) GetCharCardLimitMax() *RmCharCardInfo {
	if m != nil {
		return m.CharCardLimitMax
	}
	return nil
}

func (m *RoomCreateReq) GetCharCardLimitMin() *RmCharCardInfo {
	if m != nil {
		return m.CharCardLimitMin
	}
	return nil
}

type RoomResp struct {
	Result               *Room     `protobuf:"bytes,1,opt,name=result,proto3" json:"result,omitempty"`
	ErrorMsg             *ErrorMsg `protobuf:"bytes,2,opt,name=error_msg,json=errorMsg,proto3" json:"error_msg,omitempty"`
	XXX_NoUnkeyedLiteral struct{}  `json:"-"`
	XXX_unrecognized     []byte    `json:"-"`
	XXX_sizecache        int32     `json:"-"`
}

func (m *RoomResp) Reset()         { *m = RoomResp{} }
func (m *RoomResp) String() string { return proto.CompactTextString(m) }
func (*RoomResp) ProtoMessage()    {}
func (*RoomResp) Descriptor() ([]byte, []int) {
	return fileDescriptor_33c57e4bae7b9afd, []int{7}
}

func (m *RoomResp) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_RoomResp.Unmarshal(m, b)
}
func (m *RoomResp) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_RoomResp.Marshal(b, m, deterministic)
}
func (m *RoomResp) XXX_Merge(src proto.Message) {
	xxx_messageInfo_RoomResp.Merge(m, src)
}
func (m *RoomResp) XXX_Size() int {
	return xxx_messageInfo_RoomResp.Size(m)
}
func (m *RoomResp) XXX_DiscardUnknown() {
	xxx_messageInfo_RoomResp.DiscardUnknown(m)
}

var xxx_messageInfo_RoomResp proto.InternalMessageInfo

func (m *RoomResp) GetResult() *Room {
	if m != nil {
		return m.Result
	}
	return nil
}

func (m *RoomResp) GetErrorMsg() *ErrorMsg {
	if m != nil {
		return m.ErrorMsg
	}
	return nil
}

type RoomListResp struct {
	Result               []*RoomSH `protobuf:"bytes,1,rep,name=result,proto3" json:"result,omitempty"`
	ErrorMsg             *ErrorMsg `protobuf:"bytes,2,opt,name=error_msg,json=errorMsg,proto3" json:"error_msg,omitempty"`
	XXX_NoUnkeyedLiteral struct{}  `json:"-"`
	XXX_unrecognized     []byte    `json:"-"`
	XXX_sizecache        int32     `json:"-"`
}

func (m *RoomListResp) Reset()         { *m = RoomListResp{} }
func (m *RoomListResp) String() string { return proto.CompactTextString(m) }
func (*RoomListResp) ProtoMessage()    {}
func (*RoomListResp) Descriptor() ([]byte, []int) {
	return fileDescriptor_33c57e4bae7b9afd, []int{8}
}

func (m *RoomListResp) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_RoomListResp.Unmarshal(m, b)
}
func (m *RoomListResp) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_RoomListResp.Marshal(b, m, deterministic)
}
func (m *RoomListResp) XXX_Merge(src proto.Message) {
	xxx_messageInfo_RoomListResp.Merge(m, src)
}
func (m *RoomListResp) XXX_Size() int {
	return xxx_messageInfo_RoomListResp.Size(m)
}
func (m *RoomListResp) XXX_DiscardUnknown() {
	xxx_messageInfo_RoomListResp.DiscardUnknown(m)
}

var xxx_messageInfo_RoomListResp proto.InternalMessageInfo

func (m *RoomListResp) GetResult() []*RoomSH {
	if m != nil {
		return m.Result
	}
	return nil
}

func (m *RoomListResp) GetErrorMsg() *ErrorMsg {
	if m != nil {
		return m.ErrorMsg
	}
	return nil
}

type RoomSearchReq struct {
	// Limitation for total Card-Deck
	CostLimitMax int32 `protobuf:"varint,1,opt,name=cost_limit_max,json=costLimitMax,proto3" json:"cost_limit_max,omitempty"`
	CostLimitMin int32 `protobuf:"varint,2,opt,name=cost_limit_min,json=costLimitMin,proto3" json:"cost_limit_min,omitempty"`
	// 1vs1 or 3vs3
	CharCardNvn int32 `protobuf:"varint,3,opt,name=char_card_nvn,json=charCardNvn,proto3" json:"char_card_nvn,omitempty"`
	// Limitation for Charecter Card Cost
	CharCardLimitMax     *RmCharCardInfo `protobuf:"bytes,4,opt,name=char_card_limit_max,json=charCardLimitMax,proto3" json:"char_card_limit_max,omitempty"`
	CharCardLimitMin     *RmCharCardInfo `protobuf:"bytes,5,opt,name=char_card_limit_min,json=charCardLimitMin,proto3" json:"char_card_limit_min,omitempty"`
	Key                  string          `protobuf:"bytes,6,opt,name=key,proto3" json:"key,omitempty"`
	XXX_NoUnkeyedLiteral struct{}        `json:"-"`
	XXX_unrecognized     []byte          `json:"-"`
	XXX_sizecache        int32           `json:"-"`
}

func (m *RoomSearchReq) Reset()         { *m = RoomSearchReq{} }
func (m *RoomSearchReq) String() string { return proto.CompactTextString(m) }
func (*RoomSearchReq) ProtoMessage()    {}
func (*RoomSearchReq) Descriptor() ([]byte, []int) {
	return fileDescriptor_33c57e4bae7b9afd, []int{9}
}

func (m *RoomSearchReq) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_RoomSearchReq.Unmarshal(m, b)
}
func (m *RoomSearchReq) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_RoomSearchReq.Marshal(b, m, deterministic)
}
func (m *RoomSearchReq) XXX_Merge(src proto.Message) {
	xxx_messageInfo_RoomSearchReq.Merge(m, src)
}
func (m *RoomSearchReq) XXX_Size() int {
	return xxx_messageInfo_RoomSearchReq.Size(m)
}
func (m *RoomSearchReq) XXX_DiscardUnknown() {
	xxx_messageInfo_RoomSearchReq.DiscardUnknown(m)
}

var xxx_messageInfo_RoomSearchReq proto.InternalMessageInfo

func (m *RoomSearchReq) GetCostLimitMax() int32 {
	if m != nil {
		return m.CostLimitMax
	}
	return 0
}

func (m *RoomSearchReq) GetCostLimitMin() int32 {
	if m != nil {
		return m.CostLimitMin
	}
	return 0
}

func (m *RoomSearchReq) GetCharCardNvn() int32 {
	if m != nil {
		return m.CharCardNvn
	}
	return 0
}

func (m *RoomSearchReq) GetCharCardLimitMax() *RmCharCardInfo {
	if m != nil {
		return m.CharCardLimitMax
	}
	return nil
}

func (m *RoomSearchReq) GetCharCardLimitMin() *RmCharCardInfo {
	if m != nil {
		return m.CharCardLimitMin
	}
	return nil
}

func (m *RoomSearchReq) GetKey() string {
	if m != nil {
		return m.Key
	}
	return ""
}

func init() {
	proto.RegisterEnum("ULZProto.RoomStatus", RoomStatus_name, RoomStatus_value)
	proto.RegisterEnum("ULZProto.RoomMsg_MsgType", RoomMsg_MsgType_name, RoomMsg_MsgType_value)
	proto.RegisterType((*RmCharCardInfo)(nil), "ULZProto.RmCharCardInfo")
	proto.RegisterType((*RmUserInfo)(nil), "ULZProto.RmUserInfo")
	proto.RegisterType((*Room)(nil), "ULZProto.Room")
	proto.RegisterType((*RoomSH)(nil), "ULZProto.RoomSH")
	proto.RegisterType((*RoomMsg)(nil), "ULZProto.RoomMsg")
	proto.RegisterType((*RoomReq)(nil), "ULZProto.RoomReq")
	proto.RegisterType((*RoomCreateReq)(nil), "ULZProto.RoomCreateReq")
	proto.RegisterType((*RoomResp)(nil), "ULZProto.RoomResp")
	proto.RegisterType((*RoomListResp)(nil), "ULZProto.RoomListResp")
	proto.RegisterType((*RoomSearchReq)(nil), "ULZProto.RoomSearchReq")
}

func init() { proto.RegisterFile("message.proto", fileDescriptor_33c57e4bae7b9afd) }

var fileDescriptor_33c57e4bae7b9afd = []byte{
	// 906 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0xac, 0x56, 0xdd, 0x6e, 0xe3, 0x44,
	0x14, 0xc6, 0xf9, 0xf1, 0xcf, 0xc9, 0x0f, 0xde, 0xd9, 0x95, 0xea, 0x6e, 0x2f, 0x58, 0x59, 0x08,
	0x45, 0x08, 0x05, 0xa9, 0x70, 0xcb, 0x45, 0xdb, 0x0d, 0xd4, 0xda, 0xc4, 0x59, 0x4d, 0x1c, 0x15,
	0x56, 0x42, 0x96, 0xb1, 0x67, 0x5d, 0xab, 0xb1, 0x27, 0xcc, 0x38, 0x61, 0xfb, 0x10, 0x3c, 0x05,
	0x77, 0xbc, 0x02, 0x6f, 0xc1, 0x23, 0xf0, 0x14, 0x5c, 0xa2, 0x99, 0xb1, 0x1b, 0xb7, 0xe9, 0x8a,
	0x76, 0xb5, 0x77, 0xe7, 0x7c, 0xe7, 0xf8, 0xfc, 0x7d, 0xe7, 0x8c, 0x0c, 0x83, 0x9c, 0x70, 0x1e,
	0xa5, 0x64, 0xbc, 0x66, 0xb4, 0xa4, 0xc8, 0x5c, 0x4e, 0xdf, 0xbc, 0x16, 0xd2, 0xf3, 0x7e, 0x4c,
	0xf3, 0x9c, 0x16, 0x0a, 0x77, 0x53, 0x18, 0xe2, 0xfc, 0xec, 0x32, 0x62, 0x67, 0x11, 0x4b, 0xbc,
	0xe2, 0x2d, 0x45, 0x07, 0x60, 0xc4, 0x11, 0x4b, 0xc2, 0x2c, 0x71, 0xb4, 0x17, 0xda, 0xa8, 0x8b,
	0x75, 0xa1, 0x7a, 0x09, 0x7a, 0x06, 0xdd, 0x15, 0xd9, 0x92, 0x95, 0xd3, 0x92, 0xb0, 0x52, 0x10,
	0x82, 0x0e, 0x8b, 0x18, 0x71, 0xda, 0x12, 0x94, 0xb2, 0xc0, 0x62, 0xca, 0x4b, 0xa7, 0xa3, 0x30,
	0x21, 0xbb, 0xbf, 0x6b, 0x00, 0x38, 0x5f, 0x72, 0xc2, 0x64, 0x96, 0x21, 0xb4, 0xaa, 0x04, 0x16,
	0x6e, 0x65, 0x89, 0xf8, 0xa4, 0x88, 0x72, 0x22, 0x63, 0x5b, 0x58, 0xca, 0xbb, 0x84, 0xed, 0x66,
	0xc2, 0x23, 0xb0, 0xa2, 0x6d, 0x54, 0x86, 0x59, 0x4c, 0x0b, 0x99, 0xc1, 0xc2, 0xa6, 0x00, 0xbc,
	0x98, 0x16, 0xe2, 0x93, 0x32, 0x2b, 0x57, 0xc4, 0xe9, 0x4a, 0x83, 0x52, 0x54, 0x8d, 0xc5, 0x95,
	0xa3, 0xd7, 0x35, 0x16, 0x57, 0xee, 0x3f, 0x6d, 0xe8, 0x60, 0x4a, 0xf3, 0xbd, 0x4a, 0x6c, 0x68,
	0x5f, 0x91, 0xeb, 0xaa, 0x10, 0x21, 0xa2, 0xe7, 0x60, 0xae, 0x23, 0xce, 0x7f, 0xa3, 0x2c, 0x91,
	0xa5, 0x58, 0xf8, 0x46, 0x47, 0x23, 0xe8, 0x5c, 0xd6, 0xad, 0xf6, 0x8e, 0x9f, 0x8d, 0xeb, 0x31,
	0x8f, 0x77, 0xbd, 0x62, 0xe9, 0x81, 0xbe, 0x02, 0x3d, 0xd9, 0x90, 0x15, 0x61, 0xb2, 0xb6, 0xf7,
	0xf9, 0x56, 0x3e, 0xc2, 0x9b, 0x97, 0x51, 0xb9, 0xe1, 0x8e, 0xf1, 0x42, 0x1b, 0x0d, 0x6f, 0x79,
	0x53, 0x9a, 0x2f, 0xa4, 0x0d, 0x57, 0x3e, 0xb2, 0xed, 0x0d, 0x2b, 0xb8, 0x63, 0xaa, 0x49, 0x49,
	0x05, 0x7d, 0x0e, 0x43, 0x31, 0xfa, 0x70, 0x95, 0xe5, 0x59, 0x19, 0xe6, 0xd1, 0x3b, 0xc7, 0x92,
	0xe6, 0xbe, 0x40, 0xa7, 0x02, 0x9c, 0x45, 0xef, 0xee, 0x7a, 0x65, 0x85, 0x03, 0x77, 0xbd, 0xb2,
	0x02, 0xfd, 0x00, 0x4f, 0xe3, 0xcb, 0x88, 0x85, 0x72, 0x35, 0x76, 0x01, 0x7b, 0xb2, 0x15, 0xa7,
	0xd9, 0x4a, 0x73, 0x99, 0xb0, 0x1d, 0x57, 0xda, 0x4d, 0xba, 0xfb, 0x02, 0x65, 0x85, 0xd3, 0x7f,
	0x5c, 0xa0, 0xac, 0x40, 0x2e, 0x0c, 0x76, 0x81, 0x8a, 0x6d, 0xe1, 0x0c, 0x64, 0xd9, 0xbd, 0xda,
	0xd1, 0xdf, 0x16, 0xee, 0xdf, 0x1a, 0xe8, 0x72, 0x5c, 0xe7, 0x35, 0xad, 0xda, 0x8e, 0xd6, 0x23,
	0xb0, 0x04, 0x31, 0x61, 0x63, 0xef, 0x4c, 0x01, 0xf8, 0x62, 0xf7, 0x0e, 0xc0, 0x90, 0xc6, 0xd5,
	0xb6, 0xda, 0x3e, 0x5d, 0xa8, 0xd3, 0x2d, 0xfa, 0x0c, 0x7a, 0x8a, 0x22, 0xf5, 0x9d, 0x5a, 0x40,
	0x50, 0x90, 0xfc, 0xf2, 0x08, 0xac, 0xca, 0x61, 0xb5, 0x95, 0x54, 0x77, 0xb1, 0xa9, 0x80, 0xe9,
	0xb6, 0x41, 0xab, 0xfe, 0x18, 0x5a, 0x8d, 0x06, 0xad, 0xee, 0xbf, 0x1a, 0x18, 0xc2, 0x79, 0xc6,
	0xd3, 0x7b, 0xba, 0x3a, 0x00, 0xe3, 0x2d, 0x65, 0xb9, 0x38, 0x5f, 0xd5, 0x93, 0x2e, 0x54, 0x2f,
	0x41, 0x4f, 0xa1, 0x5b, 0x52, 0x01, 0xab, 0x15, 0xee, 0x94, 0xd4, 0x4b, 0x90, 0x03, 0x46, 0xf5,
	0x4e, 0x54, 0x9d, 0xd4, 0x2a, 0xfa, 0x16, 0xcc, 0x9c, 0xa7, 0x61, 0x79, 0xbd, 0x56, 0xc7, 0x34,
	0x3c, 0x3e, 0xbc, 0x5d, 0xeb, 0x8c, 0xa7, 0xe3, 0x19, 0x4f, 0x83, 0xeb, 0x35, 0xc1, 0x46, 0xae,
	0x04, 0xf7, 0x67, 0x30, 0x2a, 0x0c, 0x0d, 0xc0, 0x5a, 0x2e, 0x26, 0x38, 0x0c, 0x26, 0x3f, 0x06,
	0xf6, 0x27, 0xe8, 0x09, 0x0c, 0xa4, 0xba, 0x08, 0xb0, 0x77, 0xf6, 0x6a, 0x82, 0x6d, 0x0d, 0x7d,
	0x0a, 0xbd, 0xc5, 0x4f, 0x8b, 0x60, 0x32, 0x0b, 0x3d, 0xff, 0xfb, 0xb9, 0xdd, 0x6a, 0x00, 0x17,
	0x27, 0xd8, 0xb7, 0xdb, 0x68, 0x08, 0x50, 0x01, 0x13, 0x8c, 0xed, 0x8e, 0xfb, 0x9d, 0xea, 0x1c,
	0x93, 0x5f, 0xd1, 0x21, 0x98, 0x8c, 0xd2, 0x3c, 0xdc, 0xb5, 0x6f, 0x08, 0xfd, 0x95, 0x1a, 0xc1,
	0x86, 0x13, 0xd6, 0x18, 0x81, 0x50, 0xbd, 0xc4, 0xfd, 0xab, 0x05, 0x03, 0xf1, 0xfd, 0x19, 0x23,
	0x51, 0x49, 0x44, 0x94, 0xfa, 0x7c, 0xb5, 0xff, 0x3d, 0xdf, 0xfd, 0x63, 0x6a, 0x3d, 0xe8, 0x98,
	0xda, 0xf7, 0x1c, 0xd3, 0xde, 0xea, 0x76, 0xf6, 0x56, 0xf7, 0x7d, 0x07, 0xd7, 0xfd, 0x58, 0x07,
	0xa7, 0x3f, 0xf6, 0xe0, 0xdc, 0x18, 0x4c, 0x35, 0x7c, 0xbe, 0x46, 0x5f, 0x80, 0xce, 0x08, 0xdf,
	0xac, 0xea, 0xc9, 0x0d, 0x6f, 0xef, 0x06, 0xae, 0xac, 0xe8, 0x6b, 0xb0, 0x08, 0x63, 0x94, 0x85,
	0x39, 0x4f, 0xe5, 0xc0, 0x7a, 0xc7, 0x68, 0xe7, 0x3a, 0x11, 0xa6, 0x19, 0x4f, 0xb1, 0x49, 0x2a,
	0xc9, 0xcd, 0xa0, 0x2f, 0x02, 0x4c, 0x33, 0x5e, 0xca, 0x44, 0xa3, 0x46, 0xa2, 0xf6, 0xa8, 0x77,
	0x6c, 0xdf, 0x39, 0x98, 0xf3, 0x0f, 0x4f, 0xf5, 0x47, 0xb5, 0x0d, 0x0b, 0x12, 0xb1, 0xf8, 0x52,
	0x6c, 0xc3, 0x3e, 0xc7, 0xda, 0x83, 0x38, 0x6e, 0x3d, 0x84, 0xe3, 0xf6, 0x83, 0x39, 0xee, 0x7c,
	0x2c, 0x8e, 0xbb, 0x8f, 0x7e, 0x54, 0xab, 0xf7, 0x44, 0xbf, 0x79, 0x4f, 0xbe, 0xbc, 0x00, 0xd8,
	0xbd, 0x4c, 0xa8, 0x0f, 0xe6, 0xdc, 0x0f, 0x17, 0xc1, 0x09, 0x16, 0x37, 0xdd, 0x03, 0x63, 0xee,
	0x87, 0x17, 0x27, 0x5e, 0x60, 0x6b, 0xc8, 0x86, 0xfe, 0xdc, 0x0f, 0xcf, 0xe7, 0x8b, 0x20, 0x0c,
	0x96, 0xd8, 0xb7, 0x5b, 0x15, 0xf2, 0x72, 0x39, 0x99, 0x2a, 0xa4, 0x8d, 0x00, 0xf4, 0xb9, 0x1f,
	0x4e, 0xfc, 0x97, 0x76, 0xe7, 0xf4, 0x14, 0x0e, 0x33, 0x3a, 0x4e, 0xd9, 0x3a, 0x16, 0xf5, 0x9d,
	0x70, 0x4e, 0xca, 0xb1, 0xac, 0x72, 0x46, 0x93, 0x53, 0xb3, 0x86, 0x5e, 0x6b, 0x6f, 0xba, 0xf2,
	0x4f, 0xe5, 0xcf, 0xd6, 0x93, 0x3d, 0xb7, 0x5f, 0x74, 0x69, 0xfa, 0xe6, 0xbf, 0x00, 0x00, 0x00,
	0xff, 0xff, 0x20, 0xa4, 0x9d, 0x9f, 0xed, 0x08, 0x00, 0x00,
}
