// Code generated by protoc-gen-go. DO NOT EDIT.
// source: service.proto

// import "google/protobuf/empty.proto";

package proto

import (
	context "context"
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

func init() { proto.RegisterFile("service.proto", fileDescriptor_a0b84a42fa06f626) }

var fileDescriptor_a0b84a42fa06f626 = []byte{
	// 281 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x9c, 0x52, 0x4f, 0x4b, 0xc3, 0x30,
	0x14, 0xdf, 0x14, 0xa5, 0xbe, 0x39, 0xc7, 0x72, 0x11, 0x7b, 0xdc, 0x07, 0xa8, 0x63, 0x03, 0x07,
	0x7a, 0xb2, 0x22, 0xa2, 0xac, 0xd0, 0x39, 0x76, 0xd9, 0x2d, 0xa6, 0xcf, 0x12, 0x24, 0x7d, 0x35,
	0xc9, 0x04, 0xbf, 0x92, 0x9f, 0xd1, 0x83, 0x24, 0xdd, 0x94, 0xd9, 0x7a, 0x98, 0xb7, 0xbc, 0xdf,
	0x9f, 0xfc, 0xde, 0x2f, 0x04, 0xba, 0x06, 0xf5, 0x9b, 0x14, 0x18, 0x95, 0x9a, 0x2c, 0xb1, 0x60,
	0x31, 0x5d, 0xa6, 0xee, 0x14, 0x76, 0x15, 0x1a, 0xc3, 0xf3, 0x35, 0x11, 0x1e, 0x0b, 0x52, 0x8a,
	0x8a, 0x6a, 0x1a, 0x7d, 0xee, 0x43, 0xe7, 0x91, 0x48, 0xcd, 0x2b, 0x33, 0x9b, 0x00, 0xdc, 0x68,
	0xe4, 0x16, 0x1d, 0xc8, 0x4e, 0xa3, 0xcd, 0x2d, 0x91, 0x9b, 0xd7, 0x0c, 0xbe, 0x86, 0x27, 0xdb,
	0xc4, 0xa0, 0xc5, 0x2e, 0xa1, 0x73, 0x87, 0xd6, 0x0d, 0x53, 0x69, 0xec, 0x0e, 0xce, 0x61, 0x9b,
	0x8d, 0xbe, 0xbd, 0xf7, 0xc5, 0x33, 0xb1, 0xfe, 0xb6, 0xa4, 0x39, 0x6f, 0x02, 0xb0, 0x28, 0xb3,
	0x7f, 0x2c, 0x7a, 0x05, 0x3d, 0x57, 0x16, 0x75, 0xac, 0x89, 0x67, 0x82, 0x1b, 0xdb, 0x14, 0xf8,
	0x0b, 0x4a, 0x4c, 0xee, 0x37, 0x1d, 0x43, 0x67, 0x8e, 0x45, 0x96, 0x54, 0x2f, 0xca, 0xea, 0xaa,
	0xb0, 0xf7, 0x03, 0xdd, 0xaa, 0xd2, 0xbe, 0x0f, 0x5a, 0x6c, 0x08, 0xc1, 0x6c, 0x25, 0x7d, 0xbf,
	0xa6, 0xa8, 0x06, 0xc7, 0x05, 0x1c, 0xcd, 0x56, 0x52, 0xbc, 0xa4, 0x5c, 0xea, 0x5d, 0xba, 0x9d,
	0x43, 0xf0, 0x40, 0xb2, 0xf8, 0x2b, 0xa9, 0x66, 0x88, 0x63, 0x38, 0x93, 0x14, 0xe5, 0xba, 0x14,
	0x8e, 0xba, 0x36, 0x06, 0x6d, 0xe4, 0x05, 0x09, 0x65, 0x71, 0xb0, 0x81, 0xd2, 0xf6, 0xf2, 0xc0,
	0x7f, 0x97, 0x8f, 0xbd, 0x7e, 0x4d, 0xf6, 0x74, 0xe8, 0xa9, 0xf1, 0x57, 0x00, 0x00, 0x00, 0xff,
	0xff, 0xe8, 0xac, 0xd3, 0xdb, 0x81, 0x02, 0x00, 0x00,
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConn

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion4

// RoomServiceClient is the client API for RoomService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://godoc.org/google.golang.org/grpc#ClientConn.NewStream.
type RoomServiceClient interface {
	CreateRoom(ctx context.Context, in *RoomCreateReq, opts ...grpc.CallOption) (*Room, error)
	GetRoomList(ctx context.Context, in *RoomCreateReq, opts ...grpc.CallOption) (RoomService_GetRoomListClient, error)
	GetRoomInfo(ctx context.Context, in *RoomReq, opts ...grpc.CallOption) (*Room, error)
	UpdateRoom(ctx context.Context, in *RoomCreateReq, opts ...grpc.CallOption) (*Room, error)
	ServerBroadcast(ctx context.Context, in *RoomReq, opts ...grpc.CallOption) (RoomService_ServerBroadcastClient, error)
	SendMessage(ctx context.Context, in *RoomMsg, opts ...grpc.CallOption) (*Empty, error)
	QuitRoom(ctx context.Context, in *RoomReq, opts ...grpc.CallOption) (*Empty, error)
	QuickPair(ctx context.Context, in *RoomCreateReq, opts ...grpc.CallOption) (*Room, error)
	JoinRoom(ctx context.Context, in *RoomReq, opts ...grpc.CallOption) (*Room, error)
}

type roomServiceClient struct {
	cc *grpc.ClientConn
}

func NewRoomServiceClient(cc *grpc.ClientConn) RoomServiceClient {
	return &roomServiceClient{cc}
}

func (c *roomServiceClient) CreateRoom(ctx context.Context, in *RoomCreateReq, opts ...grpc.CallOption) (*Room, error) {
	out := new(Room)
	err := c.cc.Invoke(ctx, "/ULZProto.RoomService/CreateRoom", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *roomServiceClient) GetRoomList(ctx context.Context, in *RoomCreateReq, opts ...grpc.CallOption) (RoomService_GetRoomListClient, error) {
	stream, err := c.cc.NewStream(ctx, &_RoomService_serviceDesc.Streams[0], "/ULZProto.RoomService/GetRoomList", opts...)
	if err != nil {
		return nil, err
	}
	x := &roomServiceGetRoomListClient{stream}
	if err := x.ClientStream.SendMsg(in); err != nil {
		return nil, err
	}
	if err := x.ClientStream.CloseSend(); err != nil {
		return nil, err
	}
	return x, nil
}

type RoomService_GetRoomListClient interface {
	Recv() (*Room, error)
	grpc.ClientStream
}

type roomServiceGetRoomListClient struct {
	grpc.ClientStream
}

func (x *roomServiceGetRoomListClient) Recv() (*Room, error) {
	m := new(Room)
	if err := x.ClientStream.RecvMsg(m); err != nil {
		return nil, err
	}
	return m, nil
}

func (c *roomServiceClient) GetRoomInfo(ctx context.Context, in *RoomReq, opts ...grpc.CallOption) (*Room, error) {
	out := new(Room)
	err := c.cc.Invoke(ctx, "/ULZProto.RoomService/GetRoomInfo", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *roomServiceClient) UpdateRoom(ctx context.Context, in *RoomCreateReq, opts ...grpc.CallOption) (*Room, error) {
	out := new(Room)
	err := c.cc.Invoke(ctx, "/ULZProto.RoomService/UpdateRoom", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *roomServiceClient) ServerBroadcast(ctx context.Context, in *RoomReq, opts ...grpc.CallOption) (RoomService_ServerBroadcastClient, error) {
	stream, err := c.cc.NewStream(ctx, &_RoomService_serviceDesc.Streams[1], "/ULZProto.RoomService/ServerBroadcast", opts...)
	if err != nil {
		return nil, err
	}
	x := &roomServiceServerBroadcastClient{stream}
	if err := x.ClientStream.SendMsg(in); err != nil {
		return nil, err
	}
	if err := x.ClientStream.CloseSend(); err != nil {
		return nil, err
	}
	return x, nil
}

type RoomService_ServerBroadcastClient interface {
	Recv() (*RoomMsg, error)
	grpc.ClientStream
}

type roomServiceServerBroadcastClient struct {
	grpc.ClientStream
}

func (x *roomServiceServerBroadcastClient) Recv() (*RoomMsg, error) {
	m := new(RoomMsg)
	if err := x.ClientStream.RecvMsg(m); err != nil {
		return nil, err
	}
	return m, nil
}

func (c *roomServiceClient) SendMessage(ctx context.Context, in *RoomMsg, opts ...grpc.CallOption) (*Empty, error) {
	out := new(Empty)
	err := c.cc.Invoke(ctx, "/ULZProto.RoomService/SendMessage", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *roomServiceClient) QuitRoom(ctx context.Context, in *RoomReq, opts ...grpc.CallOption) (*Empty, error) {
	out := new(Empty)
	err := c.cc.Invoke(ctx, "/ULZProto.RoomService/QuitRoom", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *roomServiceClient) QuickPair(ctx context.Context, in *RoomCreateReq, opts ...grpc.CallOption) (*Room, error) {
	out := new(Room)
	err := c.cc.Invoke(ctx, "/ULZProto.RoomService/QuickPair", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *roomServiceClient) JoinRoom(ctx context.Context, in *RoomReq, opts ...grpc.CallOption) (*Room, error) {
	out := new(Room)
	err := c.cc.Invoke(ctx, "/ULZProto.RoomService/JoinRoom", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// RoomServiceServer is the server API for RoomService service.
type RoomServiceServer interface {
	CreateRoom(context.Context, *RoomCreateReq) (*Room, error)
	GetRoomList(*RoomCreateReq, RoomService_GetRoomListServer) error
	GetRoomInfo(context.Context, *RoomReq) (*Room, error)
	UpdateRoom(context.Context, *RoomCreateReq) (*Room, error)
	ServerBroadcast(*RoomReq, RoomService_ServerBroadcastServer) error
	SendMessage(context.Context, *RoomMsg) (*Empty, error)
	QuitRoom(context.Context, *RoomReq) (*Empty, error)
	QuickPair(context.Context, *RoomCreateReq) (*Room, error)
	JoinRoom(context.Context, *RoomReq) (*Room, error)
}

// UnimplementedRoomServiceServer can be embedded to have forward compatible implementations.
type UnimplementedRoomServiceServer struct {
}

func (*UnimplementedRoomServiceServer) CreateRoom(ctx context.Context, req *RoomCreateReq) (*Room, error) {
	return nil, status.Errorf(codes.Unimplemented, "method CreateRoom not implemented")
}
func (*UnimplementedRoomServiceServer) GetRoomList(req *RoomCreateReq, srv RoomService_GetRoomListServer) error {
	return status.Errorf(codes.Unimplemented, "method GetRoomList not implemented")
}
func (*UnimplementedRoomServiceServer) GetRoomInfo(ctx context.Context, req *RoomReq) (*Room, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetRoomInfo not implemented")
}
func (*UnimplementedRoomServiceServer) UpdateRoom(ctx context.Context, req *RoomCreateReq) (*Room, error) {
	return nil, status.Errorf(codes.Unimplemented, "method UpdateRoom not implemented")
}
func (*UnimplementedRoomServiceServer) ServerBroadcast(req *RoomReq, srv RoomService_ServerBroadcastServer) error {
	return status.Errorf(codes.Unimplemented, "method ServerBroadcast not implemented")
}
func (*UnimplementedRoomServiceServer) SendMessage(ctx context.Context, req *RoomMsg) (*Empty, error) {
	return nil, status.Errorf(codes.Unimplemented, "method SendMessage not implemented")
}
func (*UnimplementedRoomServiceServer) QuitRoom(ctx context.Context, req *RoomReq) (*Empty, error) {
	return nil, status.Errorf(codes.Unimplemented, "method QuitRoom not implemented")
}
func (*UnimplementedRoomServiceServer) QuickPair(ctx context.Context, req *RoomCreateReq) (*Room, error) {
	return nil, status.Errorf(codes.Unimplemented, "method QuickPair not implemented")
}
func (*UnimplementedRoomServiceServer) JoinRoom(ctx context.Context, req *RoomReq) (*Room, error) {
	return nil, status.Errorf(codes.Unimplemented, "method JoinRoom not implemented")
}

func RegisterRoomServiceServer(s *grpc.Server, srv RoomServiceServer) {
	s.RegisterService(&_RoomService_serviceDesc, srv)
}

func _RoomService_CreateRoom_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(RoomCreateReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(RoomServiceServer).CreateRoom(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/ULZProto.RoomService/CreateRoom",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(RoomServiceServer).CreateRoom(ctx, req.(*RoomCreateReq))
	}
	return interceptor(ctx, in, info, handler)
}

func _RoomService_GetRoomList_Handler(srv interface{}, stream grpc.ServerStream) error {
	m := new(RoomCreateReq)
	if err := stream.RecvMsg(m); err != nil {
		return err
	}
	return srv.(RoomServiceServer).GetRoomList(m, &roomServiceGetRoomListServer{stream})
}

type RoomService_GetRoomListServer interface {
	Send(*Room) error
	grpc.ServerStream
}

type roomServiceGetRoomListServer struct {
	grpc.ServerStream
}

func (x *roomServiceGetRoomListServer) Send(m *Room) error {
	return x.ServerStream.SendMsg(m)
}

func _RoomService_GetRoomInfo_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(RoomReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(RoomServiceServer).GetRoomInfo(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/ULZProto.RoomService/GetRoomInfo",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(RoomServiceServer).GetRoomInfo(ctx, req.(*RoomReq))
	}
	return interceptor(ctx, in, info, handler)
}

func _RoomService_UpdateRoom_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(RoomCreateReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(RoomServiceServer).UpdateRoom(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/ULZProto.RoomService/UpdateRoom",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(RoomServiceServer).UpdateRoom(ctx, req.(*RoomCreateReq))
	}
	return interceptor(ctx, in, info, handler)
}

func _RoomService_ServerBroadcast_Handler(srv interface{}, stream grpc.ServerStream) error {
	m := new(RoomReq)
	if err := stream.RecvMsg(m); err != nil {
		return err
	}
	return srv.(RoomServiceServer).ServerBroadcast(m, &roomServiceServerBroadcastServer{stream})
}

type RoomService_ServerBroadcastServer interface {
	Send(*RoomMsg) error
	grpc.ServerStream
}

type roomServiceServerBroadcastServer struct {
	grpc.ServerStream
}

func (x *roomServiceServerBroadcastServer) Send(m *RoomMsg) error {
	return x.ServerStream.SendMsg(m)
}

func _RoomService_SendMessage_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(RoomMsg)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(RoomServiceServer).SendMessage(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/ULZProto.RoomService/SendMessage",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(RoomServiceServer).SendMessage(ctx, req.(*RoomMsg))
	}
	return interceptor(ctx, in, info, handler)
}

func _RoomService_QuitRoom_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(RoomReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(RoomServiceServer).QuitRoom(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/ULZProto.RoomService/QuitRoom",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(RoomServiceServer).QuitRoom(ctx, req.(*RoomReq))
	}
	return interceptor(ctx, in, info, handler)
}

func _RoomService_QuickPair_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(RoomCreateReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(RoomServiceServer).QuickPair(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/ULZProto.RoomService/QuickPair",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(RoomServiceServer).QuickPair(ctx, req.(*RoomCreateReq))
	}
	return interceptor(ctx, in, info, handler)
}

func _RoomService_JoinRoom_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(RoomReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(RoomServiceServer).JoinRoom(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/ULZProto.RoomService/JoinRoom",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(RoomServiceServer).JoinRoom(ctx, req.(*RoomReq))
	}
	return interceptor(ctx, in, info, handler)
}

var _RoomService_serviceDesc = grpc.ServiceDesc{
	ServiceName: "ULZProto.RoomService",
	HandlerType: (*RoomServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "CreateRoom",
			Handler:    _RoomService_CreateRoom_Handler,
		},
		{
			MethodName: "GetRoomInfo",
			Handler:    _RoomService_GetRoomInfo_Handler,
		},
		{
			MethodName: "UpdateRoom",
			Handler:    _RoomService_UpdateRoom_Handler,
		},
		{
			MethodName: "SendMessage",
			Handler:    _RoomService_SendMessage_Handler,
		},
		{
			MethodName: "QuitRoom",
			Handler:    _RoomService_QuitRoom_Handler,
		},
		{
			MethodName: "QuickPair",
			Handler:    _RoomService_QuickPair_Handler,
		},
		{
			MethodName: "JoinRoom",
			Handler:    _RoomService_JoinRoom_Handler,
		},
	},
	Streams: []grpc.StreamDesc{
		{
			StreamName:    "GetRoomList",
			Handler:       _RoomService_GetRoomList_Handler,
			ServerStreams: true,
		},
		{
			StreamName:    "ServerBroadcast",
			Handler:       _RoomService_ServerBroadcast_Handler,
			ServerStreams: true,
		},
	},
	Metadata: "service.proto",
}
